// This Code is generated with AI

import { StyleSheet } from 'react-native';
import { colors } from '../../../util/colors';
import { formStyles as ui } from '../../../components/formStyles';
import { fonts } from '../../../util/fonts';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.homeBackground },
  photoRoot: { backgroundColor: colors.mealReviewBackground },
  reviewRoot: { backgroundColor: colors.mealReviewBackground },
  header: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  back: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    shadowColor: colors.navy,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 24,
    elevation: 2,
  },
  headerCopy: { flex: 1 },
  headerNote: { color: colors.homeMuted, fontSize: 10, fontFamily: fonts.poppinsRegular, marginTop: 1 },
  reviewIntro: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 24, paddingBottom: 8, gap: 8 },
  reviewIntroTitle: { color: colors.homeText, fontSize: 12, fontFamily: fonts.poppinsSemiBold },
  reviewIntroText: { color: colors.homeMuted, fontSize: 9, fontFamily: fonts.poppinsRegular },
  reviewBadge: { borderRadius: 999, backgroundColor: colors.homeSelected, paddingHorizontal: 8, paddingVertical: 5 },
  reviewBadgeText: { color: colors.homePrimary, fontSize: 8, fontFamily: fonts.poppinsSemiBold },
  confirmHint: { color: colors.homeMuted, fontSize: 9, fontFamily: fonts.poppinsRegular },
  draftNote: { color: colors.homeMuted, fontSize: 9, fontFamily: fonts.poppinsRegular, textAlign: 'center' },
  progress: { flexDirection: 'row', gap: 6, marginHorizontal: 24 },
  segment: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: colors.homeBorder,
  },
  photoSegment: { backgroundColor: colors.mealReviewBorder },
  activeSegment: { backgroundColor: colors.homePrimary },
  content: { paddingHorizontal: 24, paddingVertical: 14, gap: 10, flexGrow: 1 },
  photoContent: { gap: 16 },
  footer: { paddingHorizontal: 24, paddingTop: 8, paddingBottom: 16, gap: 10 },
  photo: {
    height: 318,
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.homeBorder,
  },
  hero: {
    backgroundColor: colors.navy,
    padding: 18,
    borderRadius: 20,
    gap: 10,
    height: 211,
  },
  heroTitle: {
    ...ui.title,
    fontSize: 20,
    lineHeight: 26,
    color: colors.homeBorder,
  },
  heroText: { ...ui.text, color: colors.surface, fontSize: 11 },
  example: { width: 112, height: 112, borderRadius: 18 },
  heroVisual: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  exampleWrap: { width: 112, height: 112 },
  exampleBadge: { position: 'absolute', top: 7, left: 7, color: colors.homePrimary, backgroundColor: colors.surface, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, fontSize: 9, fontFamily: fonts.poppinsSemiBold },
  heroGuidance: { flex: 1, gap: 10 },
  heroTip: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  heroTipIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.homeSelected, alignItems: 'center', justifyContent: 'center' },
  heroTipText: { ...ui.text, color: colors.surface, flex: 1, fontSize: 10, lineHeight: 15 },
  sourceList: { gap: 8 },
  sourceAction: { height: 60, borderRadius: 14, borderWidth: 1, borderColor: colors.mealReviewBorder, backgroundColor: colors.surface, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  manualRoute: { height: 60, borderRadius: 14, borderWidth: 1, borderColor: colors.mealReviewBorder, backgroundColor: colors.surface, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 },
  manualRouteLabel: { color: colors.homeText, fontSize: 13, fontFamily: fonts.poppinsSemiBold },
  sourceIcon: { width: 36, height: 36, borderRadius: 10, backgroundColor: colors.homeSelected, alignItems: 'center', justifyContent: 'center' },
  sourceLabel: { color: colors.homeText, fontSize: 12, fontFamily: fonts.poppinsSemiBold },
  methodPhoto: { height: 150 },
  fullPhotoHint: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 },
  fullPhotoHintText: { color: colors.homePrimary, fontSize: 10, fontFamily: fonts.poppinsSemiBold },
  photoActions: { flexDirection: 'row', gap: 8 },
  removePhotoButton: { flex: 1, height: 52, borderRadius: 14, borderWidth: 1, borderColor: colors.mealReviewBorder, backgroundColor: colors.safetySurface, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
  removePhotoText: { color: colors.error, fontSize: 14, fontFamily: fonts.poppinsSemiBold },
  localPhotoInfo: { borderRadius: 10, backgroundColor: colors.calendarEmpty, padding: 10, flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  consentSurface: { backgroundColor: colors.infoSurface, borderRadius: 12, borderWidth: 1, borderColor: colors.homeBorder, padding: 12, gap: 6 },
  methodActions: { marginHorizontal: 14, gap: 10, marginTop: 14 },
  analysisPhotoWrap: { height: 320 },
  analysisScrim: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, borderRadius: 14, backgroundColor: colors.overlay, alignItems: 'center', justifyContent: 'center' },
  analysisCard: { width: 276, borderRadius: 18, borderWidth: 1, borderColor: colors.mealReviewBorder, backgroundColor: colors.surface, padding: 18, alignItems: 'center', gap: 14 },
  analysisSpinner: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.homePrimary, alignItems: 'center', justifyContent: 'center' },
  analysisText: { color: colors.homeText, fontSize: 14, fontFamily: fonts.poppinsSemiBold },
  analysisTrack: { width: 220, height: 8, borderRadius: 999, backgroundColor: colors.homeBorder, overflow: 'hidden' },
  analysisFill: { width: '65%', height: 8, borderRadius: 999, backgroundColor: colors.homePrimary },
});
