import type { AfterMealReviewDraft, DifficultyCategory, GoalFeedback, Outcome, ReviewStep, SuggestionFeedback } from '../../../types/afterMealReview';
import type { SavedSuggestion } from '../../../types/home';
import type { FoodItem, FoodTraits, Meal, PhotoSource, TraitGroup } from '../../../types/meal';
import type { Language } from '../../../types/profile';

export type ReviewViewProps = {
  meal: Meal;
  draft: AfterMealReviewDraft;
  childName: string;
  suggestionCards: Record<string, { title: string; description: string; servingTip?: string }>;
  language: Language;
  savedSuggestions: SavedSuggestion[];
  suggestionsLoading: boolean;
  saveStatus: 'saving' | 'saved' | 'error';
  photoError: 'permission' | 'image' | null;
  picking: boolean;
  elapsedSeconds: number;
  saving: boolean;
  canContinueOutcomes: boolean;
  editingFood: FoodItem | null;
  editingTraits: FoodTraits | null;
  ingredient: string;
  customTrait: { color: string; shape: string };
  onBack: () => void;
  onGo: (step: ReviewStep) => void;
  onPick: (source: PhotoSource) => void;
  onRemovePhoto: () => void;
  onFullPhoto: (side: 'before' | 'after') => void;
  onImageError: () => void;
  onCompare: () => void;
  onCancelComparison: () => void;
  onManual: () => void;
  onSelectOutcome: (foodId: string, outcome: Outcome, ingredientId?: string) => void;
  onEditFood: (food?: FoodItem) => void;
  onRemoveFood: (foodId: string) => void;
  onChangeFood: (patch: Partial<FoodItem>) => void;
  onSaveFood: () => void;
  onCancelFoodEdit: () => void;
  onSetTraits: (traits: FoodTraits | null) => void;
  onToggleTrait: (group: TraitGroup, value: string) => void;
  onSaveTraits: () => void;
  onIngredientChange: (value: string) => void;
  onAddIngredient: () => void;
  onRemoveIngredient: (name: string) => void;
  onCustomTraitChange: (group: 'color' | 'shape', value: string) => void;
  onAddCustomTrait: (group: 'color' | 'shape') => void;
  onDifficultyInput: (foodId: string, patch: Partial<{ category: DifficultyCategory | null; value: string; note: string }>) => void;
  onAddDifficulty: (foodId: string) => void;
  onRemoveDifficulty: (foodId: string, tagId: string) => void;
  difficultyForms: Record<string, { options: readonly string[]; canAdd: boolean; showNote: boolean }>;
  onGoalFeedback: (value: GoalFeedback) => void;
  onSuggestionFeedback: (suggestionId: string, value: SuggestionFeedback) => void;
  onSave: () => void;
  onRetrySave: () => void;
  onNextSuggestion: (id: string) => void;
  onRecommend: () => void;
};
