import type { Language } from '../types/profile';

const en = {
  common: {
    brand: 'NurtureBites',
    previous: 'Previous', continue: 'Continue', add: 'Add', remove: 'Remove', edit: 'Edit',
    retry: 'Retry', saveExit: 'Save & exit', saved: 'Auto-saved', saving: 'Saving…',
    saveFailed: 'Could not save. Retry before leaving.', loading: 'Getting things ready…',
    notEntered: 'Not entered', none: 'None', other: 'Other', all: 'All',
    close: 'Close', back: 'Go back', home: 'Home', language: '한국어',
    unavailable: 'This area is not ready yet.', empty: 'No records yet',
  },
  onboarding: {
    progress: (step: number, total: number) => `STEP ${step} OF ${total}`,
    safeFoodsTitle: (name: string) => `${name}’s Safe foods`,
    reviewTitle: (name: string) => `Review ${name}’s profile`,
    titles: {
      account: 'Create your caregiver account', consent: 'Data and photo consent', child: 'Tell us about your child',
      allergies: 'Food allergies', restrictions: 'Other dietary restrictions', family: 'Foods the family includes',
      approaches: 'Dietary approaches', texture: 'Sensory Profile', smell: 'Sensory Profile',
      taste: 'Sensory Profile', presentation: 'Sensory Profile', temperature: 'Sensory Profile',
      familiarity: 'Familiarity with new foods', 'safe-foods': 'Safe foods', review: 'Review your child’s profile',
    },
    subtitles: {
      account: 'Welcome! Let’s take this one step at a time.', consent: 'Consent is needed to continue',
      child: 'A few basics help us give better recommendations and output.',
      allergies: 'Select every known allergy. Help avoid foods that should not be suggested to the child.', restrictions: 'Select other required limits or choose None.',
      family: 'Select food groups your household is comfortable including.',
      approaches: 'Are there any dietary approaches you want us to consider when suggesting food?',
      texture: 'Which food textures are often difficult?', smell: 'Are strong food smells often difficult?',
      taste: 'Which tastes are often difficult?',
      presentation: 'Are any of these presentation details important?',
      temperature: 'What food temperature does your child usually prefer?',
      familiarity: 'When your child sees a new food for the first time, what usually happens?',
      'safe-foods': 'Add foods your child reliably accepts in a familiar form. We can use these foods as familiar starting points when suggesting something new.',
      review: 'You’re in control. Edit any section now or later in Profile Settings.',
    },
    caregiverName: 'Parent or caregiver full name', email: 'Email', password: 'Password',
    passwordHint: 'Use at least 8 characters.', emailHint: 'Enter a valid email address.',
    childName: 'Nickname', ageRange: 'Age range', childFallback: 'your child',
    accountPrivacy: 'Account and core privacy', photoAnalysis: 'Photo analysis and personalization',
    aiTraining: 'AI training and model research', required: 'Required', optional: 'Optional',
    consentDescriptions: {
      accountPrivacy: 'Account details are used for identification and verification. Password protection, security, retention, account deletion and deletion timing are explained in the full privacy policy.',
      photoAnalysis: 'Meal photos and the child profile are used to analyze your meal records and personalize suggestions using sensory profile, allergies/restrictions, safe foods, meal history, feedback and learning-food progress.',
      aiTraining: 'Meal photos are used only for your meal analysis and are not used to train AI models or build research datasets without this separate consent.',
    },
    viewDetail: 'View details', consentNote: 'The app does not diagnose, calculate nutritional adequacy or replace medical advice. Allergies and caregiver decisions always come first.',
    consentPanelTitle: 'Consent to Collection and Use of Personal Information',
    consentPanelSubtitle: 'Required checks must be completed before continuing.',
    consentSafetyTitle: 'Safety and recommendation limits',
    searchCatalog: 'Search the catalog', noMatches: 'No matching catalog items',
    addOther: 'Other', otherAllergy: 'Other allergy', otherRestrictions: 'Other restrictions',
    otherFood: 'Other food', otherApproach: 'Other approach',
    otherHint: 'Add one item at a time.', selectedItems: 'Selected items',
    allergySafetyTitle: 'Safety-critical',
    allergySafetyBody: 'Always check labels, preparation and cross-contact yourself. The app does not replace medical advice.',
    treeNutsHint: 'almonds, walnuts, or cashews',
    noTexture: 'No clear texture difficulty', noTaste: 'No clear taste difficulty',
    noKnownAllergies: 'No known food allergies', noOtherRestrictions: 'No other dietary restrictions',
    noPresentation: 'No presentation preferences', noSafeFoods: 'No safe foods yet',
    foodName: 'Food name', preparation: 'Preparation', presentationNote: 'Presentation note (optional)',
    addSafeFood: 'Add safe food', safeFoodIncomplete: 'Enter a food name and preparation.',
    safeFoodExamples: 'e.g. apple slices, white bread', safeFoodNameExample: 'e.g. apple slices',
    safeFoodPreparationExample: 'e.g. sliced, mashed, warmed', safeFoodPresentationExample: 'e.g. blue bowl, cut into coins',
    safeFoodFormHint: 'Add details for a food your child can reliably accept.', multipleInput: 'multiple input available',
    choiceGuidance: {
      childName: 'Use any name your family is comfortable with.',
      age: 'We ask for an age range-not an exact birth date-to reduce unnecessary personal data.',
      restrictionsQuestion: (name: string) => `Are there any other foods or ingredients ${name} needs to avoid?`,
      restrictionsTitle: 'How we use these safely',
      restrictionsBody: 'Predefined restrictions only affect recommendations when reliable rules and food data exist. Unsupported custom restrictions are stored but do not automatically filter recommendations.',
      familyTitle: 'This isn’t about likes or dislikes',
      familyBody: 'We’ll ask about familiar and safe foods separately.',
      familyWarningTitle: 'This may not be included in the suggested meal or ingredients',
      familyWarningBody: 'There is a possibility that the preferences and approaches may not be included in the recommending meals.',
      approachesTitle: 'How approaches affect suggestions',
      approachesBody: 'Only supported approaches with clear rules affect suggestions automatically.',
      textureQuestion: (name: string) => `Which food textures are often difficult for ${name}?`,
      smellQuestion: (name: string) => `Are strong food smells often difficult for ${name}?`,
      smellExample: 'For example, strong smells from fish, cooked onions, or some cooked vegetables.',
      smellBody: 'Used for: adjusting how strongly scented foods or preparations are suggested.',
      tasteQuestion: (name: string) => `Which tastes are often difficult for ${name}?`,
      tasteBody: 'These are tendencies, not diagnoses. You can update them as you notice patterns in real meals.',
      presentationQuestion: (name: string) => `Are any of these presentation details important for ${name}?`,
      presentationExample: 'Select the ones that often affect whether your child accepts a food.',
      temperatureQuestion: (name: string) => `What food temperature does ${name} usually prefer?`,
      temperatureBody: 'This is a starting tendency. Meal records can capture what worked for each food.',
      familiarityQuestion: (name: string) => `When ${name} sees a new food for the first time, what usually happens?`,
      familiarityBody: 'This is only a general starting point—never a permanent SOS level. Progress is tracked separately for each food.',
      multiple: 'multiple select available', single: 'single select available',
    },
    choiceSubtitles: {
      restrictions: { none: 'Selecting this clears and disables all other selections.', 'gluten-free': 'Avoids foods containing gluten.', 'lactose-free': 'Limits or avoids lactose-containing foods.', 'low-fructose': 'Limits foods high in fructose.', 'casein-free': 'Avoids foods containing casein.', other: 'Add one or more custom restrictions.' },
      approaches: { none: 'Use general suggestions without a specific diet.', 'gluten-casein-free': 'Avoid wheat, barley, rye, and dairy.', 'no-added-sugar': 'Fewer sweeteners and processed extras.', 'low-fructose': 'Limits foods high in fructose.', 'low-sodium': 'Limits foods high in sodium.', ketogenic: 'High fat, moderate protein, very low carbs.', other: 'Describe a custom approach or preference.' },
      texture: { smooth: 'e.g. yogurt, puree, pudding', soft: 'e.g. mashed potato, ripe banana, soft porridge', lumpy: 'e.g. chunky soup, oatmeal with pieces', crunchy: 'e.g. crackers, raw carrots, crisp cereal', chewy: 'e.g. meat, dried fruit, gummy snacks', slippery: 'e.g. watermelon, peeled citrus, slippery noodles', mixed: 'e.g. cereal with milk, yogurt with fruit pieces', other: 'Add another texture description.' },
      taste: { bitter: 'e.g. some dark leafy vegetables', sour: 'e.g. lemon, pickles', spicy: 'e.g. chili or hot sauces', 'very-sweet': 'e.g. heavily sweetened foods', 'very-salty': 'e.g. strongly salted foods' },
      presentation: { none: 'Mutually exclusive with all options below.', color: 'For example, light or single-color foods.', shape: 'Pieces look predictable from bite to bite.', separate: 'Sauces and sides do not touch.', visible: 'Nothing hidden or mixed in.', other: 'Describe a presentation detail.' },
      temperature: { none: 'No consistent pattern across meals.', warm: 'Best when heated, but not hot.', cool: 'Often prefers food straight from the fridge.', room: 'Best after sitting out for a few minutes.', depends: 'Temperature preference changes by food type.' },
    },
    reviewChild: 'Child basics', reviewSafety: 'Safety restrictions', reviewFamily: 'Family practices',
    reviewApproaches: 'Dietary approaches', reviewSensory: 'Sensory tendencies',
    reviewSafeFoods: 'Safe foods', reviewFamiliarity: 'New-food familiarity',
    conflict: 'A safe food name matches a listed restriction. Review it before relying on that food.',
    looksGood: 'Looks good',
    start: 'Start setup', resume: 'Resume setup', editProfile: 'Edit profile',
  },
  mealCheckin: {
    titles: { details: 'Meal details', photo: 'Before-meal photo', preview: 'Check your photo', method: 'Add food items', analyzing: 'Analyzing photo', 'analysis-error': 'Analysis couldn’t finish', foods: 'Review food items', goal: 'Add an exposure goal', complete: 'Check-in saved' },
    settingTitle: 'Setting details', date: 'Meal date', month: 'Month', day: 'Day', year: 'Year', selectDate: 'Select date', dateHint: 'Today or earlier (caregiver timezone)', confirmDate: 'Confirm date', mealType: 'Meal type', setting: 'Setting',
    types: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snack: 'Snack' },
    settings: { home: 'Home', restaurant: 'Restaurant', school: 'School', others: 'Others' },
    toPhoto: 'Continue to photo', addPhoto: 'Add a before-meal photo', photoTip: 'Optional — helps capture the whole plate and lighting.',
    photoTips: ['Use good light', 'Keep the plate centered', 'Make sure the food is easy to see'], example: 'Example meal photo',
    previewBadge: 'Preview', draftSaved: 'Your draft is saved as you go.', draftLabel: 'Draft', photoReady: 'photo ready',
    camera: 'Take a photo', gallery: 'Choose from gallery', files: 'Choose from files', fileHint: 'Supported images only',
    skipPhoto: 'Skip photo, Enter foods manually', skipPhotoHint: 'Continue without a photo and add named foods only.',
    replace: 'Replace photo', removePhoto: 'Remove photo', usePhoto: 'Use this photo', fullPhoto: 'Tap to view full photo',
    localPhoto: 'This photo stays on this device until you choose Analyze photo or explicitly save it.',
    analyze: 'Analyze photo', manual: 'Enter food items manually', noPhoto: 'Continue without a photo',
    consent: 'By tapping Analyze photo, you consent to sending this meal photo to our analysis provider for this meal. It will not be used to train AI without separate consent.',
    privacy: 'How photo data is used', privacyBody: 'Analysis is optional. Photos and meal records are saved on this device. No photo is sent for AI training.',
    analyzing: 'Analyzing photo…', cancelAnalysis: 'Cancel analysis', analysisFailed: 'Analysis failed. Your photo is still saved locally.',
    permission: 'Photo access was denied. Allow access in device settings or choose another source.', imageError: 'Could not open this image. Choose another supported image.',
    loadFailed: 'Could not restore your meal draft. Retry before continuing.', saveFailed: 'Could not save the meal. Your food items and goal selection are preserved.',
    reviewRequired: 'Parent review required before confirmation', ai: 'AI suggestion', parent: 'Parent input',
    addFoodPrompt: 'Please click “add food item”', parentReviewBadge: 'PARENT REVIEW',
    emptyFoodTitle: 'No food entered yet', emptyFoodBody: 'Start by adding a food item below.',
    aiCount: (count: number) => `${count} suggested food${count === 1 ? '' : 's'}`, foodCount: (count: number) => `${count} food item${count === 1 ? '' : 's'}`,
    reviewCount: (count: number) => `${count} food${count === 1 ? '' : 's'} entered`, reviewFoodHint: 'Review the foods before continuing.',
    editMealDetails: 'Edit meal details', beforePhoto: 'Before-meal photo', editPhoto: 'Edit photo', suggestedFood: 'Suggested food',
    goalSelected: 'Selected', noHistory: 'Not enough history', reviewAiReminder: 'Please review AI suggestions before confirming.',
    usingSuggestion: 'Using a saved suggestion?', chooseSuggestion: 'Choose a suggestion', moreAboutMeal: 'More about this meal',
    confirmFoodsHint: 'Confirm foods and continue to an optional goal.',
    aiNote: 'AI suggestions are never confirmed until you review them.', empty: 'Add a food item to continue.', addFood: 'Add food item', saveFood: 'Save food',
    name: 'Food name', ingredients: 'Ingredients', addIngredient: 'Add ingredient', preparation: 'Presentation', servingNote: 'Serving note',
    reviewFood: (name: string) => `Review ${name}`, reviewItemHint: 'Confirm or adjust what was served before saving.',
    addFoodHint: 'Please click ‘save food’ to save', traitsHint: 'Optional · Select only what describes this serving.',
    traits: 'Food traits', editTraits: 'Edit all traits →', saveTraits: 'Save traits', history: 'Food history', optional: 'Optional', selectHistory: 'Select food history',
    histories: { usually: 'Usually accepted', sometimes: 'Sometimes accepted', unsure: 'Not sure' },
    groups: { texture: 'Texture', tasteType: 'Taste type', tasteIntensity: 'Taste intensity', smell: 'Smell', shape: 'Shape and size', visibility: 'Ingredient visibility', temperature: 'Temperature', color: 'Color' },
    traitModes: { texture: 'Multi-select', tasteType: 'Multi-select', tasteIntensity: 'Optional', smell: 'Single-select', shape: 'Single-select', visibility: 'Single-select', temperature: 'Single-select', color: 'Optional' },
    traitLabels: { soft: 'Soft / mushy', crunchy: 'Crunchy / crisp', chewy: 'Chewy / tough', smooth: 'Smooth / creamy', lumpy: 'Lumpy / chunky', slippery: 'Wet / slippery', mixed: 'Mixed textures', sweet: 'Sweet', salty: 'Salty', sour: 'Sour', bitter: 'Bitter', spicy: 'Spicy / hot', savory: 'Savory', mild: 'Mild', medium: 'Medium', strong: 'Strong', none: 'No noticeable smell', unsure: 'Not sure', small: 'Small', large: 'Large', sliced: 'Sliced', whole: 'Whole', consistent: 'Consistent', varied: 'Varied', visible: 'Clearly visible', partial: 'Partly visible', blended: 'Blended / not separately visible', hidden: 'Hidden', hot: 'Hot', warm: 'Warm', cool: 'Cool / chilled', room: 'Room temperature', red: 'Red', orange: 'Orange', yellow: 'Yellow', green: 'Green', white: 'White', brown: 'Brown', other: 'Other' },
    customTrait: 'Add your own', cancel: 'Cancel', confirmFoods: 'Confirm food items', goalOptional: 'Optional: choose one food to focus on this meal.',
    selectGoal: 'Select this meal as exposure goal', skipGoal: 'Skip exposure goal', tracker: 'Exposure Tracker',
    goalIntro: 'Choose one food to focus on during this meal.',
    foodForm: (preparation: string, note: string) => `Food form: ${preparation}${note ? ` · ${note}` : ''}`,
    currentComfort: 'Current comfortable step: Not recorded yet', goalPractice: 'Goal to practice: Not set',
    noGoalSelected: 'No goal selected · Choose at most one. Selecting a goal records no attempt.',
    goalLabel: 'Food Exposure Goal', goalNotSet: 'Not set',
    trackerBody: 'Track familiarity and small attempts for each food. A goal does not set an exposure stage. Record actual experiences separately.',
    ladder: ['Look', 'Interact', 'Smell', 'Touch', 'Taste / Lick', 'Swallow'],
    ladderDetails: ['Notice the food', 'Explore it nearby', 'Notice its smell', 'Touch the food', 'Taste or lick it', 'Swallow a bite'],
    done: 'Your meal check-in is saved.', awaitingReview: 'Awaiting after-meal review', afterMeal: 'Add after-meal review', backToHome: 'Back to Home', resume: 'Continue meal draft', draftReview: 'Finish check-in & review',
    missingMeal: 'This meal could not be found.',
    dateLabel: (date: string, today: boolean) => `${today ? 'Today · ' : ''}${date}`,
  },
  afterMealReview: {
    titles: { photo: 'After-meal photo', preview: 'Check your photo', compare: 'Compare before and after', comparing: 'Comparing photos', 'comparison-error': 'Analysis failed', outcomes: 'What happened with each food item?', difficulties: 'What made this food difficult?', goal: 'This meal’s exposure goal', suggestions: 'Did you try a saved suggestion?', complete: 'Review saved' },
    optional: 'Optional', photoIntro: 'Add an after-meal photo', photoRequirement: 'One photo of the whole plate',
    photoTips: ['Use good light', 'Keep the plate centered', 'Make sure the food is easy to see'],
    photoLabel: 'After-meal photo', before: 'BEFORE', after: 'AFTER', enlarge: 'Tap to enlarge',
    replace: 'Replace photo', removePhoto: 'Remove photo', usePhoto: 'Use this photo',
    photoLocal: 'This photo stays on this device until you choose to analyze or explicitly save it.',
    missingBefore: 'The before-meal photo is unavailable. You can enter outcomes manually.',
    compare: 'Compare with AI', manual: 'Enter outcomes manually', privacy: 'How photo data is used',
    consent: 'Choosing Compare with AI may send both meal photos to an analysis provider. They are not used for AI training without separate consent.',
    demo: 'Prototype comparison: suggestions are not derived from the photos. Confirm each result yourself.',
    comparing: 'Comparing photos…', cancelSafely: 'Cancel safely', elapsed: (seconds: number) => `${seconds} sec`,
    compareFailed: 'We couldn’t compare the photos. Both photos and your draft remain available.',
    retryCompare: 'Retry comparison', noSuggestions: 'No comparison suggestions were returned. Enter outcomes manually.',
    outcomeIntro: 'AI suggestions are not confirmed until you edit or select a value.',
    itemCount: (count: number) => `${count} food item${count === 1 ? '' : 's'}`,
    outcomes: { eaten: 'Eaten', tasted: 'Tasted', untouched: 'Untouched', unclear: 'Unclear' },
    suggestion: 'SUGGESTED', editInfo: 'edit info', definitions: 'Outcome definitions', gotIt: 'Got it',
    unanswered: 'Unanswered', unansweredHint: 'Answer every food and ingredient. Choose Unclear when you cannot tell.',
    definitionsIntro: 'Use what you observed. You do not need to estimate exact amounts.',
    outcomeDescriptions: { eaten: 'Confirmed swallowed amount', tasted: 'Licked or tasted, with no confirmed swallow', untouched: 'Neither tasted nor eaten; looking, smelling and touching can be recorded separately', unclear: 'You cannot determine what happened', unanswered: 'This cannot be saved. Choose Unclear when the outcome is unknown.' },
    difficultyIntro: 'Some categories allow multiple value selections.', selectCategory: 'Select category', selectValue: 'value',
    note: 'Optional note', otherValue: 'Describe your answer', addTag: '+ Add', skip: 'Skip',
    categories: { texture: 'Texture', tasteType: 'Taste type', tasteIntensity: 'Taste intensity', smell: 'Smell', color: 'Color', shape: 'Shape and size', visibility: 'Ingredient visibility', temperature: 'Temperature', notSure: 'Not sure' },
    values: { smooth: 'Smooth/creamy', soft: 'Soft/mushy', lumpy: 'Lumpy/chunky', crunchy: 'Crunchy/crisp', chewy: 'Chewy/tough', wet: 'Wet/slippery', mixed: 'Mixed textures', other: 'Other', sweet: 'Sweet', salty: 'Salty', sour: 'Sour', bitter: 'Bitter', spicy: 'Spicy/hot', mild: 'Mild', strong: 'Strong', none: 'No noticeable smell', notSure: 'Not sure', red: 'Red', orange: 'Orange', yellow: 'Yellow', green: 'Green', blue: 'Blue', purple: 'Purple', brown: 'Brown', black: 'Black', white: 'White', gray: 'Gray', consistent: 'Consistent', varied: 'Varied', note: 'Optional note', visible: 'Visible', hidden: 'Hidden', room: 'Room temperature', warm: 'Warm', cool: 'Cool / chilled' },
    goalFood: (name: string) => `Focus food: ${name}`, recordGoal: 'Record what happened',
    goalChoices: { achieved: 'Goal achieved', tried: 'Tried the goal', notYet: 'Not yet' },
    noGoal: 'No exposure goal was set for this meal.',
    savedSuggestion: 'SAVED', recommended: 'RECOMMENDED', whatToTry: 'WHAT TO TRY', whyEasier: 'WHY THIS MAY BE EASIER', servingTip: 'SERVING TIP', noServingTip: 'No serving tip was saved.',
    suggestionPrompt: 'Swipe right for yes; left for no, or use the buttons.', tried: 'Tried it', notTried: 'Did not try',
    noSavedSuggestions: 'No saved suggestions to review.', recommendedNext: 'Recommended next step',
    noNextSuggestion: 'A new recommendation is not available yet.', nextSuggestion: 'View saved suggestion',
    finish: 'Save review', saved: 'Your confirmed results were saved on this device.',
    missingMeal: 'This saved meal could not be found.', loadFailed: 'Could not restore this review. Retry before continuing.',
    saveFailed: 'Could not save the review. Your answers are preserved.', permission: 'Photo access was denied. Choose another source or update device permissions.',
    imageError: 'Could not open this image. Choose another supported image.',
  },
  recommendation: {
    title: 'Recommended next step', intro: 'One small change based on your confirmed meal record.',
    source: 'RECOMMENDED', whatToTry: 'WHAT TO TRY', whyEasier: 'WHY THIS MAY BE EASIER', servingTip: 'SERVING TIP',
    action: (name: string) => `Offer ${name} as one small, separate portion`,
    whyTasted: (name: string) => `You confirmed ${name} was tasted at this meal. This offers another chance with the same known food form.`,
    whyUntouched: (name: string) => `You confirmed ${name} was untouched at this meal. A small separate portion lets your child approach it at their own pace.`,
    whyPresentation: (name: string) => `You recorded a presentation difficulty with ${name} and said keeping foods separate matters. This keeps the known food form while changing its placement.`,
    tip: 'Keep the recorded ingredients and preparation the same; place just this portion separately.',
    safety: 'Check the food label and possible cross-contact yourself before serving. This is an idea, not a guarantee.',
    save: 'Save suggestion', skip: 'Skip suggestion', goBack: 'Go back', saved: 'Suggestion saved.',
    saving: 'Saving suggestion…', saveFailed: 'Could not save this suggestion. Retry without losing the card.',
    retry: 'Retry saving', loadFailed: 'Could not load the meal or review. Retry.',
    safetyUnverified: 'Food suggestions are paused because allergies or required restrictions are not explicitly clear or are present.',
    noSafeCandidate: 'No food has enough confirmed ingredient and preparation information for a safe suggestion.',
    mealChanged: 'This meal’s current food form no longer matches its confirmed after-meal review. Check the meal record.',
    insufficientEvidence: 'The confirmed results do not support a personalized next step yet.',
    checkProfile: 'Review profile', checkMeal: 'Review meal', retryLoad: 'Retry loading',
    allDone: 'No more suggestions for this meal.', missingRecord: 'Save the after-meal review before asking for a recommendation.',
  },
  home: {
    today: 'Today', mealLog: 'Meal Log', sos: 'SOS', ideas: 'Ideas', insight: 'Insight', profile: 'Profile',
    greetingMorning: (name: string) => `Good morning, ${name}`,
    greetingAfternoon: (name: string) => `Good afternoon, ${name}`,
    greetingEvening: (name: string) => `Good evening, ${name}`,
    nextUp: 'NEXT UP · MEAL',
    nextTitle: 'Ready when you are', nextBody: 'A meal record helps you notice what made today easier.',
    logMeal: 'Log this meal', sosTitle: 'SOS Progress',
    sosBody: 'Food experience steps you have recorded', noExposure: 'No foods are being tracked yet.',
    itemCount: (count: number) => `${count} items`,
    recommendations: 'Recommended action goals', goalsSubtitle: 'Small steps to make meals easier', noRecommendations: 'No saved suggestions yet.',
    try: 'Try', calendar: 'Meal Log Calendar', calendarSubtitle: 'Logged days in dark blue, unlogged days in light blue', logged: 'Logged', unlogged: 'Unlogged',
    calendarDayStatus: (day: number, logged: boolean) => `${day}: ${logged ? 'Logged' : 'Unlogged'}`,
    noMeals: 'No meals logged this month.', profileTitle: 'Profile',
    caregiver: 'Caregiver', child: 'Child', editProfile: 'Edit profile',
    refreshFailed: 'Could not load your records.',
  },
};

const ko = {
  common: {
    brand: 'NurtureBites',
    previous: '이전', continue: '계속', add: '추가', remove: '삭제', edit: '수정',
    retry: '다시 시도', saveExit: '저장하고 나가기', saved: '자동 저장됨', saving: '저장 중…',
    saveFailed: '저장하지 못했습니다. 나가기 전에 다시 시도해 주세요.', loading: '준비하고 있어요…',
    notEntered: '입력하지 않음', none: '해당 없음', other: '기타', all: '모두',
    close: '닫기', back: '뒤로', home: '홈', language: 'English',
    unavailable: '아직 준비 중인 영역입니다.', empty: '기록이 없습니다',
  },
  onboarding: {
    progress: (step: number, total: number) => `${total}단계 중 ${step}단계`,
    safeFoodsTitle: (name: string) => `${name}의 안심 음식`,
    reviewTitle: (name: string) => `${name}의 프로필 검토`,
    titles: {
      account: '보호자 정보 입력', consent: '개인정보 동의', child: '아이에 대해 알려주세요',
      allergies: '식품 알레르기', restrictions: '기타 식이 제한', family: '가족 식단의 식품',
      approaches: '식이 접근 방식', texture: '음식의 식감', smell: '음식의 냄새',
      taste: '맛 선호', presentation: '음식 제공 형태', temperature: '음식의 온도',
      familiarity: '새로운 음식', 'safe-foods': '안심하고 먹는 음식', review: '프로필 검토',
    },
    subtitles: {
      account: '환영합니다! 한 단계씩 진행해 볼게요.', consent: '맞춤 경험을 위한 동의가 필요합니다.',
      child: '정확한 생년월일 대신 연령대만 입력합니다.',
      allergies: '알고 있는 알레르기를 모두 선택해 주세요. 아이에게 추천하면 안 되는 음식을 피하는 데 사용합니다.', restrictions: '필수 제한을 선택하거나 해당 없음을 선택하세요.',
      family: '가족 식단에 포함하는 식품을 선택하세요. 건너뛸 수 있습니다.',
      approaches: '가족의 식이 방식을 선택하거나 해당 없음을 선택하세요.',
      texture: '어려워하는 식감이 있나요?', smell: '강한 음식 냄새가 어려운가요?',
      taste: '어려워하는 맛이 있나요? 이 답변은 진단이 아닙니다.',
      presentation: '음식의 모양이나 배치에 선호가 있나요?',
      temperature: '실제로 받아들인 온도는 이후 식사 기록에서 확인할 수 있습니다.',
      familiarity: '일반적인 시작점이며 음식별 경험 단계로 자동 설정되지 않습니다.',
      'safe-foods': '익숙한 형태로 꾸준히 먹는 음식을 추가하세요.',
      review: '저장하기 전에 내용을 확인해 주세요.',
    },
    caregiverName: '보호자 이름', email: '이메일 주소', password: '비밀번호',
    passwordHint: '8글자 이상 입력해 주세요.', emailHint: '올바른 이메일 주소를 입력해 주세요.',
    childName: '아이의 별명', ageRange: '연령대', childFallback: '아이',
    accountPrivacy: '계정 및 돌봄 정보', photoAnalysis: '사진 분석 및 개인화',
    aiTraining: 'AI 학습 및 모델 연구', required: '필수', optional: '선택',
    consentDescriptions: {
      accountPrivacy: '돌봄 설정을 위해 계정 정보와 아동 프로필을 보관합니다.',
      photoAnalysis: '식사 분석을 선택했을 때 사진과 음식 정보를 사용합니다.',
      aiTraining: '이 항목을 선택하지 않으면 모델 연구에 정보를 사용하지 않습니다.',
    },
    viewDetail: '자세히 보기', consentNote: '프로필은 기기에 저장하며 비밀번호는 저장하지 않습니다. 계속하려면 필수 항목에 동의해 주세요.',
    consentPanelTitle: '개인정보 수집 및 이용 동의',
    consentPanelSubtitle: '필수 항목에 동의해야 계속할 수 있습니다.',
    consentSafetyTitle: '안전과 신뢰',
    searchCatalog: '목록 검색', noMatches: '검색 결과가 없습니다',
    addOther: '기타', otherAllergy: '기타 알레르기', otherRestrictions: '기타 식이 제한',
    otherFood: '기타 식품', otherApproach: '기타 식이 방식',
    otherHint: '한 번에 한 항목씩 추가하세요.', selectedItems: '선택한 항목',
    allergySafetyTitle: '안전 주의',
    allergySafetyBody: '식품 표시, 조리 과정, 교차 접촉 가능성을 직접 확인하세요. 앱은 의학적 조언을 대신하지 않습니다.',
    treeNutsHint: '아몬드, 호두, 캐슈넛',
    noTexture: '뚜렷하게 어려운 식감 없음', noTaste: '뚜렷하게 어려운 맛 없음',
    noKnownAllergies: '알려진 식품 알레르기 없음', noOtherRestrictions: '기타 식이 제한 없음',
    noPresentation: '제공 형태 선호 없음', noSafeFoods: '아직 안심 음식 없음',
    foodName: '음식 이름', preparation: '조리 방법', presentationNote: '제공 메모 (선택)',
    addSafeFood: '안심 음식 추가', safeFoodIncomplete: '음식 이름과 조리 방법을 입력해 주세요.',
    safeFoodExamples: '예: 사과 조각, 흰 빵', safeFoodNameExample: '예: 사과 조각',
    safeFoodPreparationExample: '예: 얇게 썰기, 으깨기, 데우기', safeFoodPresentationExample: '예: 파란 그릇, 동전 모양으로 자르기',
    safeFoodFormHint: '아이가 편안하게 먹는 음식의 형태를 적어 주세요.', multipleInput: '여러 항목 입력 가능',
    choiceGuidance: {
      childName: '가족이 편하게 부르는 이름을 입력해 주세요.',
      age: '불필요한 개인정보 수집을 줄이기 위해 정확한 생년월일 대신 연령대를 묻습니다.',
      restrictionsQuestion: (name: string) => `${name}가 피해야 할 다른 음식이나 재료가 있나요?`,
      restrictionsTitle: '제한 사항을 안전하게 사용하는 방법',
      restrictionsBody: '정해진 제한 사항은 신뢰할 수 있는 규칙과 음식 데이터가 있을 때만 추천에 반영됩니다. 직접 추가한 제한 사항은 저장되지만 추천을 자동으로 거르지는 않습니다.',
      familyTitle: '좋아하거나 싫어하는 음식에 관한 질문이 아닙니다',
      familyBody: '익숙한 음식과 안전하게 먹는 음식은 따로 묻습니다.',
      familyWarningTitle: '추천 식사나 재료에 항상 반영되지는 않을 수 있습니다',
      familyWarningBody: '입력한 선호와 식이 방식이 모든 추천 식사에 반영되지 않을 수 있습니다.',
      approachesTitle: '식이 방식이 추천에 반영되는 방법',
      approachesBody: '명확한 규칙으로 지원하는 식이 방식만 추천에 자동 반영됩니다.',
      textureQuestion: (name: string) => `${name}가 어려워하는 음식 식감은 무엇인가요?`,
      smellQuestion: (name: string) => `${name}가 강한 음식 냄새를 어려워하나요?`,
      smellExample: '예: 생선, 익힌 양파, 일부 익힌 채소의 강한 냄새',
      smellBody: '냄새가 강한 음식이나 조리법의 추천 정도를 조정하는 데 사용합니다.',
      tasteQuestion: (name: string) => `${name}가 어려워하는 맛은 무엇인가요?`,
      tasteBody: '이 정보는 진단이 아닙니다. 실제 식사에서 관찰한 내용을 바탕으로 수정할 수 있습니다.',
      presentationQuestion: (name: string) => `${name}에게 중요한 음식 제공 형태가 있나요?`,
      presentationExample: '음식을 받아들이는 데 영향을 주는 항목을 선택해 주세요.',
      temperatureQuestion: (name: string) => `${name}가 보통 선호하는 음식 온도는 무엇인가요?`,
      temperatureBody: '시작점으로 사용합니다. 음식별로 잘 맞았던 온도는 식사 기록에서 확인할 수 있습니다.',
      familiarityQuestion: (name: string) => `${name}가 새로운 음식을 처음 보면 보통 어떻게 하나요?`,
      familiarityBody: '일반적인 시작점일 뿐 고정된 경험 단계가 아닙니다. 음식별 진행 상황은 따로 기록합니다.',
      multiple: '여러 항목 선택 가능', single: '한 항목 선택 가능',
    },
    choiceSubtitles: {
      restrictions: { none: '선택하면 다른 선택이 모두 해제됩니다.', 'gluten-free': '글루텐이 든 음식을 피합니다.', 'lactose-free': '유당이 든 음식을 제한합니다.', 'low-fructose': '과당이 많은 음식을 제한합니다.', 'casein-free': '카제인이 든 음식을 피합니다.', other: '다른 제한 사항을 추가합니다.' },
      approaches: { none: '특정 식단 없이 일반적인 제안을 받습니다.', 'gluten-casein-free': '밀, 보리, 호밀, 유제품을 피합니다.', 'no-added-sugar': '감미료와 가공 첨가물을 줄입니다.', 'low-fructose': '과당이 많은 음식을 제한합니다.', 'low-sodium': '나트륨이 많은 음식을 제한합니다.', ketogenic: '고지방, 중간 단백질, 매우 낮은 탄수화물 식단입니다.', other: '다른 식이 방식이나 선호를 적습니다.' },
      texture: { smooth: '예: 요거트, 퓌레, 푸딩', soft: '예: 으깬 감자, 익은 바나나', lumpy: '예: 건더기 수프, 오트밀', crunchy: '예: 크래커, 생당근', chewy: '예: 고기, 말린 과일', slippery: '예: 수박, 미끄러운 면', mixed: '예: 우유에 든 시리얼', other: '다른 식감을 적습니다.' },
      taste: { bitter: '예: 짙은 잎채소', sour: '예: 레몬, 피클', spicy: '예: 고추, 매운 소스', 'very-sweet': '예: 단맛이 강한 음식', 'very-salty': '예: 짠맛이 강한 음식' },
      presentation: { none: '아래 선택지와 함께 선택할 수 없습니다.', color: '예: 밝거나 한 가지 색의 음식', shape: '매번 비슷한 모양과 크기의 조각', separate: '소스와 반찬이 서로 닿지 않음', visible: '숨기거나 섞지 않은 재료', other: '다른 제공 형태를 적습니다.' },
      temperature: { none: '식사마다 일정한 패턴이 없습니다.', warm: '뜨겁지 않게 데웠을 때 좋습니다.', cool: '냉장고에서 꺼낸 차가운 음식을 선호합니다.', room: '잠시 두어 실온이 되었을 때 좋습니다.', depends: '음식마다 선호 온도가 다릅니다.' },
    },
    reviewChild: '아이 기본 정보', reviewSafety: '안전 관련 제한', reviewFamily: '가족 식단',
    reviewApproaches: '식이 방식', reviewSensory: '감각 경향',
    reviewSafeFoods: '안심 음식', reviewFamiliarity: '새 음식 친숙도',
    conflict: '안심 음식 이름이 제한 항목과 겹칩니다. 해당 음식을 다시 확인해 주세요.',
    looksGood: '확인했어요',
    start: '설정 시작하기', resume: '설정 이어하기', editProfile: '프로필 수정',
  },
  mealCheckin: {
    titles: { details: '식사 정보', photo: '식전 사진', preview: '사진 확인', method: '식사 체크인', analyzing: '사진 분석 중', 'analysis-error': '분석 실패', foods: '음식 항목 확인', goal: '음식 경험 목표 추가', complete: '식사 저장 완료' },
    settingTitle: '식사 정보', date: '식사 날짜', month: '월', day: '일', year: '연도', selectDate: '날짜 선택', dateHint: '보호자 시간대 기준 오늘 또는 이전 날짜', confirmDate: '날짜 확인', mealType: '식사 유형', setting: '장소 / 상황',
    types: { breakfast: '아침', lunch: '점심', dinner: '저녁', snack: '간식' },
    settings: { home: '집', restaurant: '식당', school: '학교', others: '기타' },
    toPhoto: '사진 추가로 계속', addPhoto: '식전 사진을 추가해 주세요', photoTip: '접시 전체가 보이는 사진 한 장을 권장합니다.',
    photoTips: ['밝은 곳에서 촬영하세요', '접시를 중앙에 놓아 주세요', '음식이 잘 보이도록 촬영하세요'], example: '식사 사진 예시',
    skipPhoto: '사진 없이 음식 직접 입력', skipPhotoHint: '사진 없이 음식 이름을 직접 추가합니다.',
    previewBadge: '미리보기', draftSaved: '초안은 진행하면서 자동 저장됩니다.', draftLabel: '초안', photoReady: '사진 준비됨',
    camera: '사진 촬영', gallery: '사진 보관함에서 선택', files: '파일에서 선택', fileHint: 'JPEG, PNG, WebP, HEIC, HEIF, AVIF 이미지만 지원',
    replace: '사진 교체', removePhoto: '사진 삭제', usePhoto: '이 사진 사용', fullPhoto: '사진 전체 화면 보기',
    localPhoto: '분석을 시작하거나 식사를 명시적으로 저장하기 전까지 사진은 기기에만 남습니다.',
    analyze: '사진 분석', manual: '음식 정보 직접 입력', noPhoto: '사진 없이 계속',
    consent: '사진 분석을 누르면 이 식사의 사진을 분석 제공자에게 전송하는 데 동의합니다. 별도의 동의 없이 AI 학습에 사용하지 않습니다.',
    privacy: '사진 사용 안내 자세히 보기', privacyBody: '사진 분석은 선택 사항입니다. 사진과 식사 기록을 기기에 저장합니다. AI 학습을 위해 사진을 전송하지 않습니다.',
    analyzing: '음식 제안을 준비하고 있어요…', cancelAnalysis: '분석 취소', analysisFailed: '사진을 분석하지 못했습니다. 사진과 초안은 유지됩니다.',
    permission: '사진 접근 권한이 없습니다. 기기 설정에서 권한을 허용하거나 다른 방법을 선택해 주세요.', imageError: '이미지를 열지 못했습니다. 지원되는 다른 사진을 선택해 주세요.',
    loadFailed: '식사 초안을 불러오지 못했습니다. 계속하기 전에 다시 시도해 주세요.', saveFailed: '식사를 저장하지 못했습니다. 확인한 음식과 목표 선택은 유지됩니다.',
    reviewRequired: '확정하기 전에 보호자 확인이 필요합니다', ai: 'AI 제안', parent: '보호자 입력',
    addFoodPrompt: '음식 항목을 추가해 주세요', parentReviewBadge: '보호자 확인',
    emptyFoodTitle: '아직 입력된 음식이 없습니다', emptyFoodBody: '아래에서 음식 항목을 추가해 주세요.',
    aiCount: (count: number) => `제안된 음식 ${count}개`, foodCount: (count: number) => `음식 ${count}개`,
    reviewCount: (count: number) => `입력한 음식 ${count}개`, reviewFoodHint: '계속하기 전에 음식 내용을 확인해 주세요.',
    editMealDetails: '식사 정보 수정', beforePhoto: '식전 사진', editPhoto: '사진 수정', suggestedFood: '제안된 음식',
    goalSelected: '선택됨', noHistory: '기록이 부족합니다', reviewAiReminder: '확정하기 전에 AI 제안을 확인해 주세요.',
    usingSuggestion: '저장한 제안을 사용했나요?', chooseSuggestion: '제안 선택', moreAboutMeal: '이 식사에 대해 더 보기',
    confirmFoodsHint: '음식을 확인하고 선택 사항인 목표로 계속합니다.',
    aiNote: 'AI 제안은 보호자가 확인하기 전까지 확정되지 않습니다.', empty: '계속하려면 음식을 추가해 주세요.', addFood: '음식 항목 추가', saveFood: '음식 저장',
    name: '음식 이름', ingredients: '재료', addIngredient: '재료 추가', preparation: '제공 형태', servingNote: '제공 메모',
    reviewFood: (name: string) => `${name} 확인`, reviewItemHint: '저장하기 전에 실제로 제공한 내용을 확인하거나 수정하세요.',
    addFoodHint: '저장하려면 음식 저장을 눌러 주세요.', traitsHint: '선택 사항 · 이번 식사에 해당하는 특성만 선택하세요.',
    traits: '음식 특성', editTraits: '전체 특성 수정 →', saveTraits: '특성 저장', history: '음식 수용 이력', optional: '선택', selectHistory: '음식 수용 이력 선택',
    histories: { usually: '대체로 먹어요', sometimes: '가끔 먹어요', unsure: '잘 모르겠어요' },
    groups: { texture: '식감', tasteType: '맛 종류', tasteIntensity: '맛 강도', smell: '냄새', shape: '모양과 크기', visibility: '재료 가시성', temperature: '온도', color: '색상' },
    traitModes: { texture: '복수 선택', tasteType: '복수 선택', tasteIntensity: '선택', smell: '단일 선택', shape: '단일 선택', visibility: '단일 선택', temperature: '단일 선택', color: '선택' },
    traitLabels: { soft: '부드럽거나 으깬', crunchy: '바삭한', chewy: '질기거나 쫄깃한', smooth: '매끈하거나 크림 같은', lumpy: '덩어리가 있는', slippery: '젖거나 미끄러운', mixed: '혼합된 식감', sweet: '단맛', salty: '짠맛', sour: '신맛', bitter: '쓴맛', spicy: '매운맛', savory: '감칠맛', mild: '약함', medium: '보통', strong: '강함', none: '뚜렷한 냄새 없음', unsure: '잘 모르겠음', small: '작음', large: '큼', sliced: '썰어서', whole: '통째로', consistent: '일관됨', varied: '다양함', visible: '분명하게 보임', partial: '부분적으로 보임', blended: '섞여서 구분되지 않음', hidden: '숨김', hot: '뜨거움', warm: '따뜻함', cool: '차가움', room: '실온', red: '빨강', orange: '주황', yellow: '노랑', green: '초록', white: '흰색', brown: '갈색', other: '기타' },
    customTrait: '직접 입력', cancel: '취소', confirmFoods: '음식 항목 확인 완료', goalOptional: '선택 사항: 이번 식사에서 집중할 음식 하나를 고르세요.',
    selectGoal: '이 식사의 음식 경험 목표로 선택', skipGoal: '목표 없이 저장', tracker: '음식 경험 기록',
    goalIntro: '이번 식사에서 집중할 음식 하나를 선택하세요.',
    foodForm: (preparation: string, note: string) => `음식 형태: ${preparation}${note ? ` · ${note}` : ''}`,
    currentComfort: '현재 편안한 단계: 아직 기록되지 않음', goalPractice: '연습할 목표: 설정되지 않음',
    noGoalSelected: '선택한 목표 없음 · 최대 하나만 선택하세요. 목표 선택만으로 시도가 기록되지는 않습니다.',
    goalLabel: '음식 경험 목표', goalNotSet: '설정하지 않음',
    trackerBody: '음식별 익숙함과 작은 시도를 기록합니다. 목표 선택만으로 경험 단계가 설정되지는 않습니다. 실제 경험을 따로 기록해 주세요.',
    ladder: ['보기', '상호작용', '냄새 맡기', '만지기', '맛보기 / 핥기', '삼키기'],
    ladderDetails: ['음식을 바라봐요', '가까이에서 살펴봐요', '음식 냄새를 맡아요', '음식을 만져봐요', '맛보거나 핥아봐요', '한 입 삼켜봐요'],
    done: '식사 체크인을 저장했습니다.', awaitingReview: '식후 검토 대기 중', afterMeal: '식후 검토 추가', backToHome: '홈으로 돌아가기', resume: '식사 초안 이어하기', draftReview: '체크인 완료 후 식후 검토',
    missingMeal: '이 식사 기록을 찾지 못했습니다.',
    dateLabel: (date: string, today: boolean) => `${today ? '오늘 · ' : ''}${date}`,
  },
  afterMealReview: {
    titles: { photo: '식후 사진', preview: '사진 확인', compare: '식전·식후 사진 비교', comparing: '사진 비교 중', 'comparison-error': '비교 실패', outcomes: '음식마다 어떤 일이 있었나요?', difficulties: '이 음식이 어려웠던 이유는?', goal: '이번 식사의 음식 경험 목표', suggestions: '저장한 제안을 시도했나요?', complete: '식후 검토 저장 완료' },
    optional: '선택 사항', photoIntro: '식후 사진을 추가해 주세요', photoRequirement: '접시 전체가 보이는 사진 한 장',
    photoTips: ['밝은 곳에서 촬영하세요', '접시를 중앙에 놓아 주세요', '음식이 잘 보이도록 촬영하세요'],
    photoLabel: '식후 사진', before: '식전', after: '식후', enlarge: '눌러서 크게 보기',
    replace: '사진 교체', removePhoto: '사진 삭제', usePhoto: '이 사진 사용',
    photoLocal: '분석하거나 명시적으로 저장하기 전까지 사진은 이 기기에 남습니다.',
    missingBefore: '식전 사진을 사용할 수 없습니다. 결과를 직접 입력할 수 있습니다.',
    compare: 'AI로 비교', manual: '결과 직접 입력', privacy: '사진 사용 안내',
    consent: 'AI 비교를 선택하면 두 식사 사진이 분석 제공자에게 전송될 수 있습니다. 별도 동의 없이 AI 학습에 사용하지 않습니다.',
    demo: '프로토타입 비교: 제안은 사진에서 판독한 결과가 아닙니다. 결과를 직접 확인해 주세요.',
    comparing: '사진을 비교하고 있어요…', cancelSafely: '안전하게 취소', elapsed: (seconds: number) => `${seconds}초`,
    compareFailed: '사진을 비교하지 못했습니다. 두 사진과 초안은 그대로 남아 있습니다.',
    retryCompare: '다시 비교', noSuggestions: '비교 제안이 없습니다. 결과를 직접 입력해 주세요.',
    outcomeIntro: 'AI 제안은 값을 선택하거나 수정하기 전까지 확정되지 않습니다.',
    itemCount: (count: number) => `음식 ${count}개`,
    outcomes: { eaten: '먹음', tasted: '맛봄', untouched: '먹거나 맛보지 않음', unclear: '확인 어려움' },
    suggestion: '제안', editInfo: '정보 수정', definitions: '결과 설명', gotIt: '확인했어요',
    unanswered: '미응답', unansweredHint: '모든 음식과 재료에 답해 주세요. 판단하기 어려우면 확인 어려움을 선택하세요.',
    definitionsIntro: '직접 관찰한 내용을 선택하세요. 정확한 양을 추정할 필요는 없습니다.',
    outcomeDescriptions: { eaten: '삼킨 양이 확인됨', tasted: '핥거나 맛봤지만 삼킨 것은 확인되지 않음', untouched: '먹거나 맛보지 않음. 보기·냄새 맡기·만지기는 별도로 기록 가능', unclear: '무슨 일이 있었는지 판단할 수 없음', unanswered: '이 상태로는 저장할 수 없습니다. 모르면 확인 어려움을 선택하세요.' },
    difficultyIntro: '일부 카테고리는 여러 값을 선택할 수 있습니다.', selectCategory: '카테고리 선택', selectValue: '값',
    note: '선택 메모', otherValue: '직접 입력', addTag: '+ 추가', skip: '건너뛰기',
    categories: { texture: '식감', tasteType: '맛 종류', tasteIntensity: '맛 강도', smell: '냄새', color: '색', shape: '모양과 크기', visibility: '재료 가시성', temperature: '온도', notSure: '잘 모르겠음' },
    values: { smooth: '매끄럽고 크림 같음', soft: '부드럽고 무름', lumpy: '덩어리가 있음', crunchy: '바삭함', chewy: '질김', wet: '젖고 미끄러움', mixed: '혼합 식감', other: '기타', sweet: '단맛', salty: '짠맛', sour: '신맛', bitter: '쓴맛', spicy: '매운맛', mild: '약함', strong: '강함', none: '뚜렷한 냄새 없음', notSure: '잘 모르겠음', red: '빨강', orange: '주황', yellow: '노랑', green: '초록', blue: '파랑', purple: '보라', brown: '갈색', black: '검정', white: '흰색', gray: '회색', consistent: '일정함', varied: '다양함', note: '선택 메모', visible: '보임', hidden: '숨김', room: '실온', warm: '따뜻함', cool: '차가움' },
    goalFood: (name: string) => `목표 음식: ${name}`, recordGoal: '실제로 한 일 기록',
    goalChoices: { achieved: '목표 달성', tried: '목표 시도', notYet: '아직 시도하지 않음' },
    noGoal: '이번 식사에는 음식 경험 목표를 설정하지 않았습니다.',
    savedSuggestion: '저장됨', recommended: '추천', whatToTry: '시도할 일', whyEasier: '이유', servingTip: '제공 팁', noServingTip: '저장된 제공 팁이 없습니다.',
    suggestionPrompt: '오른쪽으로 밀면 시도함, 왼쪽으로 밀면 시도하지 않음입니다. 버튼도 사용할 수 있습니다.', tried: '시도했어요', notTried: '시도하지 않았어요',
    noSavedSuggestions: '확인할 저장 제안이 없습니다.', recommendedNext: '다음 추천 단계',
    noNextSuggestion: '새 추천은 아직 준비되지 않았습니다.', nextSuggestion: '저장된 제안 보기',
    finish: '검토 저장', saved: '확정한 결과를 이 기기에 저장했습니다.',
    missingMeal: '저장된 식사를 찾지 못했습니다.', loadFailed: '식후 검토를 복원하지 못했습니다. 다시 시도해 주세요.',
    saveFailed: '식후 검토를 저장하지 못했습니다. 입력 내용은 유지됩니다.', permission: '사진 접근 권한이 없습니다. 다른 경로를 선택하거나 기기 권한을 확인해 주세요.',
    imageError: '이미지를 열지 못했습니다. 지원되는 다른 사진을 선택해 주세요.',
  },
  recommendation: {
    title: '다음 추천 단계', intro: '보호자가 확인한 식사 기록을 바탕으로 한 가지 작은 변화를 제안합니다.',
    source: '추천', whatToTry: '시도할 일', whyEasier: '이유', servingTip: '제공 팁',
    action: (name: string) => `${name}을(를) 작은 양으로 따로 담아 제공하기`,
    whyTasted: (name: string) => `이번 식사에서 ${name}을(를) 맛본 것으로 확인했습니다. 같은 음식 형태를 다시 접할 기회를 만들 수 있습니다.`,
    whyUntouched: (name: string) => `이번 식사에서 ${name}을(를) 먹거나 맛보지 않은 것으로 확인했습니다. 작은 양을 따로 두면 아이가 자기 속도로 살펴볼 수 있습니다.`,
    whyPresentation: (name: string) => `${name}의 제공 형태가 어려웠다고 기록했고 음식이 닿지 않는 것이 중요하다고 답했습니다. 확인된 음식 형태는 유지하고 놓는 위치만 바꿉니다.`,
    tip: '기록한 재료와 조리 방법은 그대로 두고, 이 음식만 작은 양으로 따로 놓아주세요.',
    safety: '제공 전 식품 표시와 교차 접촉 가능성을 직접 확인해 주세요. 이 제안은 결과를 보장하지 않습니다.',
    save: '제안 저장', skip: '넘기기', goBack: '돌아가기', saved: '제안을 저장했습니다.',
    saving: '제안 저장 중…', saveFailed: '제안을 저장하지 못했습니다. 현재 카드를 유지했습니다.',
    retry: '저장 다시 시도', loadFailed: '식사 또는 식후 기록을 불러오지 못했습니다. 다시 시도해 주세요.',
    safetyUnverified: '알레르기나 필수 식이 제한이 명확히 확인되지 않았거나 등록되어 있어 음식 제안을 보류합니다.',
    noSafeCandidate: '재료와 조리 정보를 충분히 확인한 음식이 없어 안전한 제안을 만들 수 없습니다.',
    mealChanged: '현재 음식 형태가 확정한 식후 기록과 일치하지 않습니다. 식사 기록을 확인해 주세요.',
    insufficientEvidence: '확정된 결과만으로는 개인화된 다음 단계를 설명하기 어렵습니다.',
    checkProfile: '프로필 확인', checkMeal: '식사 기록 확인', retryLoad: '다시 불러오기',
    allDone: '이번 식사에서 더 볼 제안이 없습니다.', missingRecord: '추천을 보려면 식후 검토를 먼저 저장해 주세요.',
  },
  home: {
    today: '오늘', mealLog: '식사 기록', sos: 'SOS', ideas: '아이디어', insight: '인사이트', profile: '프로필',
    greetingMorning: (name: string) => `좋은 아침이에요, ${name}님`,
    greetingAfternoon: (name: string) => `좋은 오후예요, ${name}님`,
    greetingEvening: (name: string) => `좋은 저녁이에요, ${name}님`,
    nextUp: '다음 식사', nextTitle: '준비됐을 때 시작하세요', nextBody: '식사 기록으로 오늘 편했던 점을 살펴볼 수 있어요.',
    logMeal: '식사 기록하기', sosTitle: 'SOS 진행', sosBody: '기록한 음식 경험 단계',
    noExposure: '아직 추적 중인 음식이 없습니다.', itemCount: (count: number) => `${count}개`,
    recommendations: '추천 목표', goalsSubtitle: '식사를 더 편하게 만드는 작은 시도', noRecommendations: '저장한 제안이 없습니다.',
    try: '살펴보기', calendar: '식사 기록 달력', calendarSubtitle: '기록한 날은 진한 파랑, 그 외 날짜는 연한 파랑', logged: '기록 있음', unlogged: '기록 없음',
    calendarDayStatus: (day: number, logged: boolean) => `${day}일: ${logged ? '기록 있음' : '기록 없음'}`,
    noMeals: '이번 달 식사 기록이 없습니다.', profileTitle: '프로필',
    caregiver: '보호자', child: '아이', editProfile: '프로필 수정',
    refreshFailed: '기록을 불러오지 못했습니다.',
  },
};

export const strings = { en, ko };
export function copyFor(language: Language) { return strings[language]; }

type Label = { en: string; ko: string };
type Option = { id: string; label: Label };
export type OptionGroup = 'age' | 'allergies' | 'allergyCatalog' | 'restrictions' | 'restrictionCatalog' |
  'family' | 'familyCatalog' | 'approaches' | 'approachCatalog' | 'texture' | 'smell' |
  'taste' | 'presentation' | 'temperature' | 'familiarity';

const options: Record<OptionGroup, Option[]> = {
  age: [
    ['under-2', 'Under 2 years', '2세 미만'], ['2-3', '2-3 years', '2–3세'],
    ['4-5', '4-5 years', '4–5세'], ['6-8', '6-8 years', '6–8세'],
    ['9-12', '9-12 years', '9–12세'], ['13-plus', '13+ years', '13세 이상'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  allergies: [
    ['peanut', 'Peanuts', '땅콩'], ['tree-nut', 'Tree nuts', '견과류'],
    ['milk', 'Milk / Dairy', '우유 / 유제품'], ['egg', 'Eggs', '달걀'],
    ['soy', 'Soy', '대두'], ['wheat', 'Wheat', '밀'],
    ['fish', 'Fish', '생선'], ['shellfish', 'Shellfish', '갑각류'], ['sesame', 'Sesame', '참깨'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  allergyCatalog: [
    ['coconut', 'Coconut', '코코넛'], ['buckwheat', 'Buckwheat', '메밀'],
    ['kiwi', 'Kiwi', '키위'], ['strawberry', 'Strawberry', '딸기'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  restrictions: [
    ['gluten-free', 'Gluten-free', '글루텐 제한'], ['lactose-free', 'Lactose-free', '유당 제한'],
    ['low-fructose', 'Low fructose', '저과당식'], ['casein-free', 'Casein-free', '카제인 제한'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  restrictionCatalog: [
    ['no-pork', 'No pork', '돼지고기 제외'], ['no-beef', 'No beef', '소고기 제외'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  family: [
    ['dairy', 'Dairy', '유제품'], ['eggs', 'Eggs', '달걀'],
    ['seafood', 'Seafood', '해산물'], ['poultry', 'Poultry', '가금류'],
    ['red-meat', 'Red meat', '붉은 고기'], ['legumes-soy', 'Legumes / soy', '콩류 / 대두'],
    ['nuts-seeds', 'Nuts / seeds', '견과류 / 씨앗류'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  familyCatalog: [
    ['legumes', 'Legumes', '콩류'], ['eggs', 'Eggs', '달걀'], ['seaweed', 'Seaweed', '해조류'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  approaches: [
    ['gluten-casein-free', 'Gluten-free and casein-free', '글루텐·카제인 제한'],
    ['no-added-sugar', 'No added sugar / limited artificial additives', '첨가당 없음 / 인공첨가물 제한'],
    ['low-fructose', 'Low-fructose', '저과당식'], ['low-sodium', 'Low sodium', '저염식'],
    ['ketogenic', 'Ketogenic', '케톤 식이'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  approachCatalog: [
    ['pescatarian', 'Pescatarian', '페스코'], ['mediterranean', 'Mediterranean', '지중해식'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  texture: [
    ['smooth', 'Smooth / creamy', '매끈하거나 크림 같은'],
    ['soft', 'Soft / mushy', '부드럽거나 으깬'], ['lumpy', 'Lumpy / chunky', '덩어리가 있는'],
    ['crunchy', 'Crunchy / crisp', '바삭한'], ['chewy', 'Chewy / tough', '질기거나 쫄깃한'],
    ['slippery', 'Wet / slippery', '젖거나 미끄러운'], ['mixed', 'Mixed textures', '혼합된 식감'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  smell: [
    ['yes', 'Yes', '네'], ['sometimes', 'Sometimes', '가끔'],
    ['no', 'No', '아니요'], ['unsure', 'Not sure', '잘 모르겠어요'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  taste: [
    ['bitter', 'Bitter', '쓴맛'], ['sour', 'Sour', '신맛'],
    ['spicy', 'Spicy / hot', '맵거나 뜨거운 맛'],
    ['very-sweet', 'Very sweet', '매우 단맛'], ['very-salty', 'Very salty', '매우 짠맛'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  presentation: [
    ['color', 'Specific colors', '특정 색상'], ['shape', 'Consistent shapes and sizes', '일관된 모양과 크기'],
    ['separate', 'Foods kept separate', '음식이 닿지 않게'],
    ['visible', 'Ingredients clearly visible', '재료가 분명하게 보이게'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  temperature: [
    ['none', 'No clear preference', '뚜렷한 선호 없음'], ['warm', 'Warm', '따뜻하게'],
    ['cool', 'Cool / chilled', '차갑게'], ['room', 'Room temperature', '상온'],
    ['depends', 'It depends on the food', '음식마다 달라요'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  familiarity: [
    ['tastes', 'Usually tastes a new food', '새 음식을 보통 맛봐요'],
    ['plate', 'Okay on the plate, may not taste', '접시에 놓여도 괜찮지만 먹지 않을 수 있어요'],
    ['nearby', 'Prefers it nearby but separate', '가까이 두되 분리하는 편이에요'],
    ['removed', 'Wants it removed', '치워 주길 원해요'],
    ['varies', 'Varies by food', '음식마다 달라요'], ['unsure', 'Not sure', '잘 모르겠어요'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
};

export function optionsFor(group: OptionGroup, language: Language) {
  return options[group].map(({ id, label }) => ({ id, label: label[language] }));
}

const legacyOptionLabels: Partial<Record<OptionGroup, Record<string, { en: string; ko: string }>>> = {
  age: {
    toddler: { en: '1–3 years', ko: '1–3세' }, preschool: { en: '4–6 years', ko: '4–6세' },
    school: { en: '7–12 years', ko: '7–12세' }, teen: { en: '13–17 years', ko: '13–17세' },
  },
  restrictions: { 'low-sodium': { en: 'Low sodium', ko: '저염식' } },
  family: {
    vegetables: { en: 'Vegetables', ko: '채소' }, fruits: { en: 'Fruits', ko: '과일' },
    grains: { en: 'Grains', ko: '곡류' }, meat: { en: 'Meat', ko: '육류' },
    fish: { en: 'Fish', ko: '생선' }, legumes: { en: 'Legumes', ko: '콩류' }, seaweed: { en: 'Seaweed', ko: '해조류' },
  },
  approaches: {
    vegetarian: { en: 'Vegetarian', ko: '채식' }, vegan: { en: 'Vegan', ko: '비건' },
    halal: { en: 'Halal', ko: '할랄' }, kosher: { en: 'Kosher', ko: '코셔' },
    pescatarian: { en: 'Pescatarian', ko: '페스코' }, mediterranean: { en: 'Mediterranean', ko: '지중해식' },
  },
  taste: { sweet: { en: 'Sweet', ko: '단맛' }, salty: { en: 'Salty', ko: '짠맛' } },
};

export function labelFor(group: OptionGroup, id: string, language: Language): string {
  if (id === 'none') return strings[language].common.none;
  const catalog: Partial<Record<OptionGroup, OptionGroup>> = {
    allergies: 'allergyCatalog', restrictions: 'restrictionCatalog',
    family: 'familyCatalog', approaches: 'approachCatalog',
  };
  return options[group].find((option) => option.id === id)?.label[language]
    ?? (catalog[group] ? options[catalog[group]].find((option) => option.id === id)?.label[language] : undefined)
    ?? legacyOptionLabels[group]?.[id]?.[language]
    ?? id;
}
