import type { Language } from '../types/profile';

const en = {
  common: {
    brand: 'NurtureBites',
    previous: 'Previous', continue: 'Continue', add: 'Add', remove: 'Remove', edit: 'Edit',
    retry: 'Retry', saveExit: 'Save & exit', saved: 'Auto-saved', saving: 'Saving…',
    saveFailed: 'Could not save. Retry before leaving.', loading: 'Getting things ready…',
    notEntered: 'Not entered', none: 'None', other: 'Other', all: 'All',
    close: 'Close', back: 'Go back', home: 'Home', language: '한국어',
    unavailable: 'This area is not ready yet.', empty: 'No records yet',
  },
  onboarding: {
    progress: (step: number, total: number) => `STEP ${step} OF ${total}`,
    titles: {
      account: 'Create your account', consent: 'Your privacy choices', child: 'Tell us about your child',
      allergies: 'Food allergies', restrictions: 'Other dietary restrictions', family: 'Foods in family meals',
      approaches: 'Dietary approaches', texture: 'Food textures', smell: 'Food smells',
      taste: 'Taste preferences', presentation: 'How food is served', temperature: 'Serving temperature',
      familiarity: 'New foods', 'safe-foods': 'Safe foods', review: 'Review your profile',
    },
    subtitles: {
      account: 'Welcome! Let’s take this one step at a time.', consent: 'Consent is needed to personalize your experience.',
      child: 'We only need an age range, not a birth date.',
      allergies: 'Select every known allergy. Help avoid foods that should not be suggested to the child.', restrictions: 'Select other required limits or choose None.',
      family: 'What foods are part of family meals? This step is optional.',
      approaches: 'Choose your family’s dietary approach or None.',
      texture: 'Which textures are difficult?', smell: 'Are strong food smells difficult?',
      taste: 'Which tastes are difficult? These answers are not a diagnosis.',
      presentation: 'How does your child prefer food to look or be arranged?',
      temperature: 'Actual accepted temperatures can be checked in meal records later.',
      familiarity: 'This is a general starting point, not an exposure stage for any food.',
      'safe-foods': 'Add foods your child consistently accepts in a familiar form.',
      review: 'Check the details before saving your profile.',
    },
    caregiverName: 'Your name', email: 'Email address', password: 'Password',
    passwordHint: 'Use at least 8 characters.', emailHint: 'Enter a valid email address.',
    childName: 'Child nickname', ageRange: 'Age range',
    accountPrivacy: 'Account and care privacy', photoAnalysis: 'Photo analysis and personalization',
    aiTraining: 'AI training and model research', required: 'Required', optional: 'Optional',
    consentDescriptions: {
      accountPrivacy: 'Account details and child profile are kept to support your care setup.',
      photoAnalysis: 'Meal photos and food details are used when you choose to analyze a meal.',
      aiTraining: 'Your information is not used for model research without this choice.',
    },
    viewDetail: 'View detail', consentNote: 'Your profile is saved on this device; passwords are not stored. Accept both required choices to continue.',
    consentPanelTitle: 'Consent to Collection and Use of Personal Information',
    consentPanelSubtitle: 'Required choices must be accepted to continue.',
    consentSafetyTitle: 'Safety and trust',
    searchCatalog: 'Search the catalog', noMatches: 'No matching catalog items',
    addOther: 'Other', otherAllergy: 'Other allergy', otherRestrictions: 'Other restrictions',
    otherFood: 'Other food', otherApproach: 'Other approach',
    otherHint: 'Add one item at a time.', selectedItems: 'Selected items',
    allergySafetyTitle: 'Safety-critical',
    allergySafetyBody: 'Always check labels, preparation and cross-contact yourself. The app does not replace medical advice.',
    treeNutsHint: 'almonds, walnuts, or cashews',
    noTexture: 'No clear texture difficulty', noTaste: 'No clear taste difficulty',
    noKnownAllergies: 'No known food allergies', noOtherRestrictions: 'No other dietary restrictions',
    noPresentation: 'No presentation preferences', noSafeFoods: 'No safe foods yet',
    foodName: 'Food name', preparation: 'Preparation', presentationNote: 'Presentation note (optional)',
    addSafeFood: 'Add safe food', safeFoodIncomplete: 'Enter a food name and preparation.',
    reviewChild: 'Child basics', reviewSafety: 'Safety restrictions', reviewFamily: 'Family practices',
    reviewApproaches: 'Dietary approaches', reviewSensory: 'Sensory tendencies',
    reviewSafeFoods: 'Safe foods', reviewFamiliarity: 'New-food familiarity',
    conflict: 'A safe food name matches a listed restriction. Review it before relying on that food.',
    looksGood: 'Looks good',
    start: 'Start setup', resume: 'Resume setup', editProfile: 'Edit profile',
  },
  mealCheckin: {
    titles: { details: 'Meal details', photo: 'Before-meal photo', preview: 'Review your photo', method: 'Meal Check-in', analyzing: 'Analyzing photo', 'analysis-error': 'Analysis failed', foods: 'Review food items', goal: 'Add an exposure goal', complete: 'Meal saved' },
    settingTitle: 'Setting of the meal', date: 'Meal date', month: 'Month', day: 'Day', year: 'Year', confirmDate: 'Confirm date', mealType: 'Meal type', setting: 'Setting',
    types: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snack: 'Snack' },
    settings: { home: 'Home', restaurant: 'Restaurant', school: 'School', others: 'Others' },
    toPhoto: 'Continue to photo', addPhoto: 'Add a before-meal photo', photoTip: 'One photo of the whole plate is recommended.',
    photoTips: ['Use good light', 'Keep the plate centered', 'Make sure the food is easy to see'], example: 'Example meal photo',
    camera: 'Take a photo', gallery: 'Choose from gallery', files: 'Choose from files', fileHint: 'JPEG, PNG, WebP, HEIC, HEIF or AVIF images only',
    replace: 'Replace photo', removePhoto: 'Remove photo', usePhoto: 'Use this photo', fullPhoto: 'View full photo',
    localPhoto: 'Your photo stays on this device until you choose to analyze or explicitly save the meal.',
    analyze: 'Analyze photo', manual: 'Enter food items manually', noPhoto: 'Continue without a photo',
    consent: 'By choosing Analyze photo, you agree to send this meal photo to the analysis provider. It is never used for AI training without separate consent.',
    privacy: 'Photo use details', privacyBody: 'Analysis is optional. Photos and meal records are saved on this device. No photo is sent for AI training.',
    analyzing: 'Preparing food suggestions…', cancelAnalysis: 'Cancel analysis', analysisFailed: 'Could not analyze this photo. Your photo and draft are still here.',
    permission: 'Photo access was denied. Allow access in device settings or choose another source.', imageError: 'Could not open this image. Choose another supported image.',
    loadFailed: 'Could not restore your meal draft. Retry before continuing.', saveFailed: 'Could not save the meal. Your food items and goal selection are preserved.',
    reviewRequired: 'Parent review required before confirmation', ai: 'AI suggestion', parent: 'Parent input',
    aiCount: (count: number) => `${count} suggested food item${count === 1 ? '' : 's'}`, foodCount: (count: number) => `${count} food item${count === 1 ? '' : 's'}`,
    aiNote: 'AI suggestions are never confirmed until you review them.', empty: 'Add a food item to continue.', addFood: 'Add food item', saveFood: 'Save food',
    name: 'Food name', ingredients: 'Ingredients', addIngredient: 'Add ingredient', preparation: 'Presentation / preparation', servingNote: 'Serving note',
    traits: 'Food traits', editTraits: 'Edit all traits →', saveTraits: 'Save traits', history: 'Food history',
    histories: { usually: 'Usually accepted', sometimes: 'Sometimes accepted', unsure: 'Not sure' },
    groups: { texture: 'Texture', tasteType: 'Taste type', tasteIntensity: 'Taste intensity', smell: 'Smell', shape: 'Shape and size', visibility: 'Ingredient visibility', temperature: 'Temperature', color: 'Color' },
    traitLabels: { soft: 'Soft', crunchy: 'Crunchy', chewy: 'Chewy', smooth: 'Smooth', mixed: 'Mixed', sweet: 'Sweet', salty: 'Salty', sour: 'Sour', bitter: 'Bitter', savory: 'Savory', mild: 'Mild', medium: 'Medium', strong: 'Strong', small: 'Small', large: 'Large', sliced: 'Sliced', whole: 'Whole', visible: 'Visible', hidden: 'Hidden', warm: 'Warm', cool: 'Cool / chilled', room: 'Room temperature', red: 'Red', orange: 'Orange', yellow: 'Yellow', green: 'Green', white: 'White', brown: 'Brown' },
    customTrait: 'Add your own', cancel: 'Cancel', confirmFoods: 'Confirm food items', goalOptional: 'Optional: choose one food to focus on this meal.',
    selectGoal: 'Select this meal as exposure goal', skipGoal: 'Skip exposure goal', tracker: 'Exposure Tracker',
    trackerBody: 'Track familiarity and small attempts for each food. A goal does not set an exposure stage. Record actual experiences separately.',
    ladder: ['Look', 'Interact', 'Smell', 'Touch', 'Taste / Lick', 'Swallow'],
    ladderDetails: ['Notice the food', 'Explore it nearby', 'Notice its smell', 'Touch the food', 'Taste or lick it', 'Swallow a bite'],
    done: 'Meal saved on this device.', afterMeal: 'After-meal Review', resume: 'Continue meal draft', draftReview: 'Finish check-in & review',
    missingMeal: 'This meal could not be found.',
    dateLabel: (date: string, today: boolean) => `${today ? 'Today · ' : ''}${date}`,
  },
  afterMealReview: {
    titles: { photo: 'After-meal photo', preview: 'Check your photo', compare: 'Compare before and after', comparing: 'Comparing photos', 'comparison-error': 'Analysis failed', outcomes: 'What happened with each food item?', difficulties: 'What made this food difficult?', goal: 'This meal’s exposure goal', suggestions: 'Did you try a saved suggestion?', complete: 'Review saved' },
    optional: 'Optional', photoIntro: 'Add an after-meal photo', photoRequirement: 'One photo of the whole plate',
    photoTips: ['Use good light', 'Keep the plate centered', 'Make sure the food is easy to see'],
    photoLabel: 'After-meal photo', before: 'BEFORE', after: 'AFTER', enlarge: 'Tap to enlarge',
    replace: 'Replace photo', removePhoto: 'Remove photo', usePhoto: 'Use this photo',
    photoLocal: 'This photo stays on this device until you choose to analyze or explicitly save it.',
    missingBefore: 'The before-meal photo is unavailable. You can enter outcomes manually.',
    compare: 'Compare with AI', manual: 'Enter outcomes manually', privacy: 'How photo data is used',
    consent: 'Choosing Compare with AI may send both meal photos to an analysis provider. They are not used for AI training without separate consent.',
    demo: 'Prototype comparison: suggestions are not derived from the photos. Confirm each result yourself.',
    comparing: 'Comparing photos…', cancelSafely: 'Cancel safely', elapsed: (seconds: number) => `${seconds} sec`,
    compareFailed: 'We couldn’t compare the photos. Both photos and your draft remain available.',
    retryCompare: 'Retry comparison', noSuggestions: 'No comparison suggestions were returned. Enter outcomes manually.',
    outcomeIntro: 'AI suggestions are not confirmed until you edit or select a value.',
    itemCount: (count: number) => `${count} food item${count === 1 ? '' : 's'}`,
    outcomes: { eaten: 'Eaten', tasted: 'Tasted', untouched: 'Untouched', unclear: 'Unclear' },
    suggestion: 'SUGGESTED', editInfo: 'edit info', definitions: 'Outcome definitions', gotIt: 'Got it',
    unanswered: 'Unanswered', unansweredHint: 'Answer every food and ingredient. Choose Unclear when you cannot tell.',
    definitionsIntro: 'Use what you observed. You do not need to estimate exact amounts.',
    outcomeDescriptions: { eaten: 'Confirmed swallowed amount', tasted: 'Licked or tasted, with no confirmed swallow', untouched: 'Neither tasted nor eaten; looking, smelling and touching can be recorded separately', unclear: 'You cannot determine what happened', unanswered: 'This cannot be saved. Choose Unclear when the outcome is unknown.' },
    difficultyIntro: 'Some categories allow multiple value selections.', selectCategory: 'Select category', selectValue: 'value',
    note: 'Optional note', otherValue: 'Describe your answer', addTag: '+ Add', skip: 'Skip',
    categories: { texture: 'Texture', tasteType: 'Taste type', tasteIntensity: 'Taste intensity', smell: 'Smell', color: 'Color', shape: 'Shape and size', visibility: 'Ingredient visibility', temperature: 'Temperature', notSure: 'Not sure' },
    values: { smooth: 'Smooth/creamy', soft: 'Soft/mushy', lumpy: 'Lumpy/chunky', crunchy: 'Crunchy/crisp', chewy: 'Chewy/tough', wet: 'Wet/slippery', mixed: 'Mixed textures', other: 'Other', sweet: 'Sweet', salty: 'Salty', sour: 'Sour', bitter: 'Bitter', spicy: 'Spicy/hot', mild: 'Mild', strong: 'Strong', none: 'No noticeable smell', notSure: 'Not sure', red: 'Red', orange: 'Orange', yellow: 'Yellow', green: 'Green', blue: 'Blue', purple: 'Purple', brown: 'Brown', black: 'Black', white: 'White', gray: 'Gray', consistent: 'Consistent', varied: 'Varied', note: 'Optional note', visible: 'Visible', hidden: 'Hidden', room: 'Room temperature', warm: 'Warm', cool: 'Cool / chilled' },
    goalFood: (name: string) => `Focus food: ${name}`, recordGoal: 'Record what happened',
    goalChoices: { achieved: 'Goal achieved', tried: 'Tried the goal', notYet: 'Not yet' },
    noGoal: 'No exposure goal was set for this meal.',
    savedSuggestion: 'SAVED', recommended: 'RECOMMENDED', whatToTry: 'WHAT TO TRY', whyEasier: 'WHY THIS MAY BE EASIER', servingTip: 'SERVING TIP', noServingTip: 'No serving tip was saved.',
    suggestionPrompt: 'Swipe right for yes; left for no, or use the buttons.', tried: 'Tried it', notTried: 'Did not try',
    noSavedSuggestions: 'No saved suggestions to review.', recommendedNext: 'Recommended next step',
    noNextSuggestion: 'A new recommendation is not available yet.', nextSuggestion: 'View saved suggestion',
    finish: 'Save review', saved: 'Your confirmed results were saved on this device.',
    missingMeal: 'This saved meal could not be found.', loadFailed: 'Could not restore this review. Retry before continuing.',
    saveFailed: 'Could not save the review. Your answers are preserved.', permission: 'Photo access was denied. Choose another source or update device permissions.',
    imageError: 'Could not open this image. Choose another supported image.',
  },
  recommendation: {
    title: 'Recommended next step', intro: 'One small change based on your confirmed meal record.',
    source: 'RECOMMENDED', whatToTry: 'WHAT TO TRY', whyEasier: 'WHY THIS MAY BE EASIER', servingTip: 'SERVING TIP',
    action: (name: string) => `Offer ${name} as one small, separate portion`,
    whyTasted: (name: string) => `You confirmed ${name} was tasted at this meal. This offers another chance with the same known food form.`,
    whyUntouched: (name: string) => `You confirmed ${name} was untouched at this meal. A small separate portion lets your child approach it at their own pace.`,
    whyPresentation: (name: string) => `You recorded a presentation difficulty with ${name} and said keeping foods separate matters. This keeps the known food form while changing its placement.`,
    tip: 'Keep the recorded ingredients and preparation the same; place just this portion separately.',
    safety: 'Check the food label and possible cross-contact yourself before serving. This is an idea, not a guarantee.',
    save: 'Save suggestion', skip: 'Skip suggestion', goBack: 'Go back', saved: 'Suggestion saved.',
    saving: 'Saving suggestion…', saveFailed: 'Could not save this suggestion. Retry without losing the card.',
    retry: 'Retry saving', loadFailed: 'Could not load the meal or review. Retry.',
    safetyUnverified: 'Food suggestions are paused because allergies or required restrictions are not explicitly clear or are present.',
    noSafeCandidate: 'No food has enough confirmed ingredient and preparation information for a safe suggestion.',
    mealChanged: 'This meal’s current food form no longer matches its confirmed after-meal review. Check the meal record.',
    insufficientEvidence: 'The confirmed results do not support a personalized next step yet.',
    checkProfile: 'Review profile', checkMeal: 'Review meal', retryLoad: 'Retry loading',
    allDone: 'No more suggestions for this meal.', missingRecord: 'Save the after-meal review before asking for a recommendation.',
  },
  home: {
    today: 'Today', mealLog: 'Meal Log', sos: 'SOS', ideas: 'Ideas', insight: 'Insight', profile: 'Profile',
    greetingMorning: (name: string) => `Good morning, ${name}`,
    greetingAfternoon: (name: string) => `Good afternoon, ${name}`,
    greetingEvening: (name: string) => `Good evening, ${name}`,
    nextUp: 'NEXT UP · MEAL',
    nextTitle: 'Ready when you are', nextBody: 'A meal record helps you notice what made today easier.',
    logMeal: 'Log this meal', sosTitle: 'SOS Progress',
    sosBody: 'Food experience steps you have recorded', noExposure: 'No foods are being tracked yet.',
    itemCount: (count: number) => `${count} items`,
    recommendations: 'Recommended action goals', goalsSubtitle: 'Small steps to make meals easier', noRecommendations: 'No saved suggestions yet.',
    try: 'Try', calendar: 'Meal Log Calendar', calendarSubtitle: 'Logged days in dark blue, unlogged days in light blue', logged: 'Logged', unlogged: 'Unlogged',
    calendarDayStatus: (day: number, logged: boolean) => `${day}: ${logged ? 'Logged' : 'Unlogged'}`,
    noMeals: 'No meals logged this month.', profileTitle: 'Profile',
    caregiver: 'Caregiver', child: 'Child', editProfile: 'Edit profile',
    refreshFailed: 'Could not load your records.',
  },
};

const ko = {
  common: {
    brand: 'NurtureBites',
    previous: '이전', continue: '계속', add: '추가', remove: '삭제', edit: '수정',
    retry: '다시 시도', saveExit: '저장하고 나가기', saved: '자동 저장됨', saving: '저장 중…',
    saveFailed: '저장하지 못했습니다. 나가기 전에 다시 시도해 주세요.', loading: '준비하고 있어요…',
    notEntered: '입력하지 않음', none: '해당 없음', other: '기타', all: '모두',
    close: '닫기', back: '뒤로', home: '홈', language: 'English',
    unavailable: '아직 준비 중인 영역입니다.', empty: '기록이 없습니다',
  },
  onboarding: {
    progress: (step: number, total: number) => `${total}단계 중 ${step}단계`,
    titles: {
      account: '보호자 정보 입력', consent: '개인정보 동의', child: '아이에 대해 알려주세요',
      allergies: '식품 알레르기', restrictions: '기타 식이 제한', family: '가족 식단의 식품',
      approaches: '식이 접근 방식', texture: '음식의 식감', smell: '음식의 냄새',
      taste: '맛 선호', presentation: '음식 제공 형태', temperature: '음식의 온도',
      familiarity: '새로운 음식', 'safe-foods': '안심하고 먹는 음식', review: '프로필 검토',
    },
    subtitles: {
      account: '환영합니다! 한 단계씩 진행해 볼게요.', consent: '맞춤 경험을 위한 동의가 필요합니다.',
      child: '정확한 생년월일 대신 연령대만 입력합니다.',
      allergies: '알고 있는 알레르기를 모두 선택해 주세요. 아이에게 추천하면 안 되는 음식을 피하는 데 사용합니다.', restrictions: '필수 제한을 선택하거나 해당 없음을 선택하세요.',
      family: '가족 식단에 포함하는 식품을 선택하세요. 건너뛸 수 있습니다.',
      approaches: '가족의 식이 방식을 선택하거나 해당 없음을 선택하세요.',
      texture: '어려워하는 식감이 있나요?', smell: '강한 음식 냄새가 어려운가요?',
      taste: '어려워하는 맛이 있나요? 이 답변은 진단이 아닙니다.',
      presentation: '음식의 모양이나 배치에 선호가 있나요?',
      temperature: '실제로 받아들인 온도는 이후 식사 기록에서 확인할 수 있습니다.',
      familiarity: '일반적인 시작점이며 음식별 경험 단계로 자동 설정되지 않습니다.',
      'safe-foods': '익숙한 형태로 꾸준히 먹는 음식을 추가하세요.',
      review: '저장하기 전에 내용을 확인해 주세요.',
    },
    caregiverName: '보호자 이름', email: '이메일 주소', password: '비밀번호',
    passwordHint: '8글자 이상 입력해 주세요.', emailHint: '올바른 이메일 주소를 입력해 주세요.',
    childName: '아이의 별명', ageRange: '연령대',
    accountPrivacy: '계정 및 돌봄 정보', photoAnalysis: '사진 분석 및 개인화',
    aiTraining: 'AI 학습 및 모델 연구', required: '필수', optional: '선택',
    consentDescriptions: {
      accountPrivacy: '돌봄 설정을 위해 계정 정보와 아동 프로필을 보관합니다.',
      photoAnalysis: '식사 분석을 선택했을 때 사진과 음식 정보를 사용합니다.',
      aiTraining: '이 항목을 선택하지 않으면 모델 연구에 정보를 사용하지 않습니다.',
    },
    viewDetail: '자세히 보기', consentNote: '프로필은 기기에 저장하며 비밀번호는 저장하지 않습니다. 계속하려면 필수 항목에 동의해 주세요.',
    consentPanelTitle: '개인정보 수집 및 이용 동의',
    consentPanelSubtitle: '필수 항목에 동의해야 계속할 수 있습니다.',
    consentSafetyTitle: '안전과 신뢰',
    searchCatalog: '목록 검색', noMatches: '검색 결과가 없습니다',
    addOther: '기타', otherAllergy: '기타 알레르기', otherRestrictions: '기타 식이 제한',
    otherFood: '기타 식품', otherApproach: '기타 식이 방식',
    otherHint: '한 번에 한 항목씩 추가하세요.', selectedItems: '선택한 항목',
    allergySafetyTitle: '안전 주의',
    allergySafetyBody: '식품 표시, 조리 과정, 교차 접촉 가능성을 직접 확인하세요. 앱은 의학적 조언을 대신하지 않습니다.',
    treeNutsHint: '아몬드, 호두, 캐슈넛',
    noTexture: '뚜렷하게 어려운 식감 없음', noTaste: '뚜렷하게 어려운 맛 없음',
    noKnownAllergies: '알려진 식품 알레르기 없음', noOtherRestrictions: '기타 식이 제한 없음',
    noPresentation: '제공 형태 선호 없음', noSafeFoods: '아직 안심 음식 없음',
    foodName: '음식 이름', preparation: '조리 방법', presentationNote: '제공 메모 (선택)',
    addSafeFood: '안심 음식 추가', safeFoodIncomplete: '음식 이름과 조리 방법을 입력해 주세요.',
    reviewChild: '아이 기본 정보', reviewSafety: '안전 관련 제한', reviewFamily: '가족 식단',
    reviewApproaches: '식이 방식', reviewSensory: '감각 경향',
    reviewSafeFoods: '안심 음식', reviewFamiliarity: '새 음식 친숙도',
    conflict: '안심 음식 이름이 제한 항목과 겹칩니다. 해당 음식을 다시 확인해 주세요.',
    looksGood: '확인했어요',
    start: '설정 시작하기', resume: '설정 이어하기', editProfile: '프로필 수정',
  },
  mealCheckin: {
    titles: { details: '식사 정보', photo: '식전 사진', preview: '사진 확인', method: '식사 체크인', analyzing: '사진 분석 중', 'analysis-error': '분석 실패', foods: '음식 항목 확인', goal: '음식 경험 목표 추가', complete: '식사 저장 완료' },
    settingTitle: '식사 상황을 알려주세요', date: '식사 날짜', month: '월', day: '일', year: '연도', confirmDate: '날짜 확인', mealType: '식사 유형', setting: '장소 / 상황',
    types: { breakfast: '아침', lunch: '점심', dinner: '저녁', snack: '간식' },
    settings: { home: '집', restaurant: '식당', school: '학교', others: '기타' },
    toPhoto: '사진 추가로 계속', addPhoto: '식전 사진을 추가해 주세요', photoTip: '접시 전체가 보이는 사진 한 장을 권장합니다.',
    photoTips: ['밝은 곳에서 촬영하세요', '접시를 중앙에 놓아 주세요', '음식이 잘 보이도록 촬영하세요'], example: '식사 사진 예시',
    camera: '사진 촬영', gallery: '사진 보관함에서 선택', files: '파일에서 선택', fileHint: 'JPEG, PNG, WebP, HEIC, HEIF, AVIF 이미지만 지원',
    replace: '사진 교체', removePhoto: '사진 삭제', usePhoto: '이 사진 사용', fullPhoto: '사진 전체 화면 보기',
    localPhoto: '분석을 시작하거나 식사를 명시적으로 저장하기 전까지 사진은 기기에만 남습니다.',
    analyze: '사진 분석', manual: '음식 정보 직접 입력', noPhoto: '사진 없이 계속',
    consent: '사진 분석을 누르면 이 식사의 사진을 분석 제공자에게 전송하는 데 동의합니다. 별도의 동의 없이 AI 학습에 사용하지 않습니다.',
    privacy: '사진 사용 안내 자세히 보기', privacyBody: '사진 분석은 선택 사항입니다. 사진과 식사 기록을 기기에 저장합니다. AI 학습을 위해 사진을 전송하지 않습니다.',
    analyzing: '음식 제안을 준비하고 있어요…', cancelAnalysis: '분석 취소', analysisFailed: '사진을 분석하지 못했습니다. 사진과 초안은 유지됩니다.',
    permission: '사진 접근 권한이 없습니다. 기기 설정에서 권한을 허용하거나 다른 방법을 선택해 주세요.', imageError: '이미지를 열지 못했습니다. 지원되는 다른 사진을 선택해 주세요.',
    loadFailed: '식사 초안을 불러오지 못했습니다. 계속하기 전에 다시 시도해 주세요.', saveFailed: '식사를 저장하지 못했습니다. 확인한 음식과 목표 선택은 유지됩니다.',
    reviewRequired: '확정하기 전에 보호자 확인이 필요합니다', ai: 'AI 제안', parent: '보호자 입력',
    aiCount: (count: number) => `제안된 음식 ${count}개`, foodCount: (count: number) => `음식 ${count}개`,
    aiNote: 'AI 제안은 보호자가 확인하기 전까지 확정되지 않습니다.', empty: '계속하려면 음식을 추가해 주세요.', addFood: '음식 항목 추가', saveFood: '음식 저장',
    name: '음식 이름', ingredients: '재료', addIngredient: '재료 추가', preparation: '제공 형태 / 조리 방법', servingNote: '제공 메모',
    traits: '음식 특성', editTraits: '전체 특성 수정 →', saveTraits: '특성 저장', history: '음식 수용 이력',
    histories: { usually: '대체로 먹어요', sometimes: '가끔 먹어요', unsure: '잘 모르겠어요' },
    groups: { texture: '식감', tasteType: '맛 종류', tasteIntensity: '맛 강도', smell: '냄새', shape: '모양과 크기', visibility: '재료 가시성', temperature: '온도', color: '색상' },
    traitLabels: { soft: '부드러움', crunchy: '바삭함', chewy: '쫄깃함', smooth: '매끈함', mixed: '혼합', sweet: '단맛', salty: '짠맛', sour: '신맛', bitter: '쓴맛', savory: '감칠맛', mild: '약함', medium: '보통', strong: '강함', small: '작음', large: '큼', sliced: '썰어서', whole: '통째로', visible: '보임', hidden: '숨김', warm: '따뜻함', cool: '차가움', room: '실온', red: '빨강', orange: '주황', yellow: '노랑', green: '초록', white: '흰색', brown: '갈색' },
    customTrait: '직접 입력', cancel: '취소', confirmFoods: '음식 항목 확인 완료', goalOptional: '선택 사항: 이번 식사에서 집중할 음식 하나를 고르세요.',
    selectGoal: '이 식사의 음식 경험 목표로 선택', skipGoal: '목표 없이 저장', tracker: '음식 경험 기록',
    trackerBody: '음식별 익숙함과 작은 시도를 기록합니다. 목표 선택만으로 경험 단계가 설정되지는 않습니다. 실제 경험을 따로 기록해 주세요.',
    ladder: ['보기', '상호작용', '냄새 맡기', '만지기', '맛보기 / 핥기', '삼키기'],
    ladderDetails: ['음식을 바라봐요', '가까이에서 살펴봐요', '음식 냄새를 맡아요', '음식을 만져봐요', '맛보거나 핥아봐요', '한 입 삼켜봐요'],
    done: '식사 기록을 기기에 저장했습니다.', afterMeal: '식후 검토', resume: '식사 초안 이어하기', draftReview: '체크인 완료 후 식후 검토',
    missingMeal: '이 식사 기록을 찾지 못했습니다.',
    dateLabel: (date: string, today: boolean) => `${today ? '오늘 · ' : ''}${date}`,
  },
  afterMealReview: {
    titles: { photo: '식후 사진', preview: '사진 확인', compare: '식전·식후 사진 비교', comparing: '사진 비교 중', 'comparison-error': '비교 실패', outcomes: '음식마다 어떤 일이 있었나요?', difficulties: '이 음식이 어려웠던 이유는?', goal: '이번 식사의 음식 경험 목표', suggestions: '저장한 제안을 시도했나요?', complete: '식후 검토 저장 완료' },
    optional: '선택 사항', photoIntro: '식후 사진을 추가해 주세요', photoRequirement: '접시 전체가 보이는 사진 한 장',
    photoTips: ['밝은 곳에서 촬영하세요', '접시를 중앙에 놓아 주세요', '음식이 잘 보이도록 촬영하세요'],
    photoLabel: '식후 사진', before: '식전', after: '식후', enlarge: '눌러서 크게 보기',
    replace: '사진 교체', removePhoto: '사진 삭제', usePhoto: '이 사진 사용',
    photoLocal: '분석하거나 명시적으로 저장하기 전까지 사진은 이 기기에 남습니다.',
    missingBefore: '식전 사진을 사용할 수 없습니다. 결과를 직접 입력할 수 있습니다.',
    compare: 'AI로 비교', manual: '결과 직접 입력', privacy: '사진 사용 안내',
    consent: 'AI 비교를 선택하면 두 식사 사진이 분석 제공자에게 전송될 수 있습니다. 별도 동의 없이 AI 학습에 사용하지 않습니다.',
    demo: '프로토타입 비교: 제안은 사진에서 판독한 결과가 아닙니다. 결과를 직접 확인해 주세요.',
    comparing: '사진을 비교하고 있어요…', cancelSafely: '안전하게 취소', elapsed: (seconds: number) => `${seconds}초`,
    compareFailed: '사진을 비교하지 못했습니다. 두 사진과 초안은 그대로 남아 있습니다.',
    retryCompare: '다시 비교', noSuggestions: '비교 제안이 없습니다. 결과를 직접 입력해 주세요.',
    outcomeIntro: 'AI 제안은 값을 선택하거나 수정하기 전까지 확정되지 않습니다.',
    itemCount: (count: number) => `음식 ${count}개`,
    outcomes: { eaten: '먹음', tasted: '맛봄', untouched: '먹거나 맛보지 않음', unclear: '확인 어려움' },
    suggestion: '제안', editInfo: '정보 수정', definitions: '결과 설명', gotIt: '확인했어요',
    unanswered: '미응답', unansweredHint: '모든 음식과 재료에 답해 주세요. 판단하기 어려우면 확인 어려움을 선택하세요.',
    definitionsIntro: '직접 관찰한 내용을 선택하세요. 정확한 양을 추정할 필요는 없습니다.',
    outcomeDescriptions: { eaten: '삼킨 양이 확인됨', tasted: '핥거나 맛봤지만 삼킨 것은 확인되지 않음', untouched: '먹거나 맛보지 않음. 보기·냄새 맡기·만지기는 별도로 기록 가능', unclear: '무슨 일이 있었는지 판단할 수 없음', unanswered: '이 상태로는 저장할 수 없습니다. 모르면 확인 어려움을 선택하세요.' },
    difficultyIntro: '일부 카테고리는 여러 값을 선택할 수 있습니다.', selectCategory: '카테고리 선택', selectValue: '값',
    note: '선택 메모', otherValue: '직접 입력', addTag: '+ 추가', skip: '건너뛰기',
    categories: { texture: '식감', tasteType: '맛 종류', tasteIntensity: '맛 강도', smell: '냄새', color: '색', shape: '모양과 크기', visibility: '재료 가시성', temperature: '온도', notSure: '잘 모르겠음' },
    values: { smooth: '매끄럽고 크림 같음', soft: '부드럽고 무름', lumpy: '덩어리가 있음', crunchy: '바삭함', chewy: '질김', wet: '젖고 미끄러움', mixed: '혼합 식감', other: '기타', sweet: '단맛', salty: '짠맛', sour: '신맛', bitter: '쓴맛', spicy: '매운맛', mild: '약함', strong: '강함', none: '뚜렷한 냄새 없음', notSure: '잘 모르겠음', red: '빨강', orange: '주황', yellow: '노랑', green: '초록', blue: '파랑', purple: '보라', brown: '갈색', black: '검정', white: '흰색', gray: '회색', consistent: '일정함', varied: '다양함', note: '선택 메모', visible: '보임', hidden: '숨김', room: '실온', warm: '따뜻함', cool: '차가움' },
    goalFood: (name: string) => `목표 음식: ${name}`, recordGoal: '실제로 한 일 기록',
    goalChoices: { achieved: '목표 달성', tried: '목표 시도', notYet: '아직 시도하지 않음' },
    noGoal: '이번 식사에는 음식 경험 목표를 설정하지 않았습니다.',
    savedSuggestion: '저장됨', recommended: '추천', whatToTry: '시도할 일', whyEasier: '이유', servingTip: '제공 팁', noServingTip: '저장된 제공 팁이 없습니다.',
    suggestionPrompt: '오른쪽으로 밀면 시도함, 왼쪽으로 밀면 시도하지 않음입니다. 버튼도 사용할 수 있습니다.', tried: '시도했어요', notTried: '시도하지 않았어요',
    noSavedSuggestions: '확인할 저장 제안이 없습니다.', recommendedNext: '다음 추천 단계',
    noNextSuggestion: '새 추천은 아직 준비되지 않았습니다.', nextSuggestion: '저장된 제안 보기',
    finish: '검토 저장', saved: '확정한 결과를 이 기기에 저장했습니다.',
    missingMeal: '저장된 식사를 찾지 못했습니다.', loadFailed: '식후 검토를 복원하지 못했습니다. 다시 시도해 주세요.',
    saveFailed: '식후 검토를 저장하지 못했습니다. 입력 내용은 유지됩니다.', permission: '사진 접근 권한이 없습니다. 다른 경로를 선택하거나 기기 권한을 확인해 주세요.',
    imageError: '이미지를 열지 못했습니다. 지원되는 다른 사진을 선택해 주세요.',
  },
  recommendation: {
    title: '다음 추천 단계', intro: '보호자가 확인한 식사 기록을 바탕으로 한 가지 작은 변화를 제안합니다.',
    source: '추천', whatToTry: '시도할 일', whyEasier: '이유', servingTip: '제공 팁',
    action: (name: string) => `${name}을(를) 작은 양으로 따로 담아 제공하기`,
    whyTasted: (name: string) => `이번 식사에서 ${name}을(를) 맛본 것으로 확인했습니다. 같은 음식 형태를 다시 접할 기회를 만들 수 있습니다.`,
    whyUntouched: (name: string) => `이번 식사에서 ${name}을(를) 먹거나 맛보지 않은 것으로 확인했습니다. 작은 양을 따로 두면 아이가 자기 속도로 살펴볼 수 있습니다.`,
    whyPresentation: (name: string) => `${name}의 제공 형태가 어려웠다고 기록했고 음식이 닿지 않는 것이 중요하다고 답했습니다. 확인된 음식 형태는 유지하고 놓는 위치만 바꿉니다.`,
    tip: '기록한 재료와 조리 방법은 그대로 두고, 이 음식만 작은 양으로 따로 놓아주세요.',
    safety: '제공 전 식품 표시와 교차 접촉 가능성을 직접 확인해 주세요. 이 제안은 결과를 보장하지 않습니다.',
    save: '제안 저장', skip: '넘기기', goBack: '돌아가기', saved: '제안을 저장했습니다.',
    saving: '제안 저장 중…', saveFailed: '제안을 저장하지 못했습니다. 현재 카드를 유지했습니다.',
    retry: '저장 다시 시도', loadFailed: '식사 또는 식후 기록을 불러오지 못했습니다. 다시 시도해 주세요.',
    safetyUnverified: '알레르기나 필수 식이 제한이 명확히 확인되지 않았거나 등록되어 있어 음식 제안을 보류합니다.',
    noSafeCandidate: '재료와 조리 정보를 충분히 확인한 음식이 없어 안전한 제안을 만들 수 없습니다.',
    mealChanged: '현재 음식 형태가 확정한 식후 기록과 일치하지 않습니다. 식사 기록을 확인해 주세요.',
    insufficientEvidence: '확정된 결과만으로는 개인화된 다음 단계를 설명하기 어렵습니다.',
    checkProfile: '프로필 확인', checkMeal: '식사 기록 확인', retryLoad: '다시 불러오기',
    allDone: '이번 식사에서 더 볼 제안이 없습니다.', missingRecord: '추천을 보려면 식후 검토를 먼저 저장해 주세요.',
  },
  home: {
    today: '오늘', mealLog: '식사 기록', sos: 'SOS', ideas: '아이디어', insight: '인사이트', profile: '프로필',
    greetingMorning: (name: string) => `좋은 아침이에요, ${name}님`,
    greetingAfternoon: (name: string) => `좋은 오후예요, ${name}님`,
    greetingEvening: (name: string) => `좋은 저녁이에요, ${name}님`,
    nextUp: '다음 식사', nextTitle: '준비됐을 때 시작하세요', nextBody: '식사 기록으로 오늘 편했던 점을 살펴볼 수 있어요.',
    logMeal: '식사 기록하기', sosTitle: 'SOS 진행', sosBody: '기록한 음식 경험 단계',
    noExposure: '아직 추적 중인 음식이 없습니다.', itemCount: (count: number) => `${count}개`,
    recommendations: '추천 목표', goalsSubtitle: '식사를 더 편하게 만드는 작은 시도', noRecommendations: '저장한 제안이 없습니다.',
    try: '살펴보기', calendar: '식사 기록 달력', calendarSubtitle: '기록한 날은 진한 파랑, 그 외 날짜는 연한 파랑', logged: '기록 있음', unlogged: '기록 없음',
    calendarDayStatus: (day: number, logged: boolean) => `${day}일: ${logged ? '기록 있음' : '기록 없음'}`,
    noMeals: '이번 달 식사 기록이 없습니다.', profileTitle: '프로필',
    caregiver: '보호자', child: '아이', editProfile: '프로필 수정',
    refreshFailed: '기록을 불러오지 못했습니다.',
  },
};

export const strings = { en, ko };
export function copyFor(language: Language) { return strings[language]; }

type Label = { en: string; ko: string };
type Option = { id: string; label: Label };
export type OptionGroup = 'age' | 'allergies' | 'allergyCatalog' | 'restrictions' | 'restrictionCatalog' |
  'family' | 'familyCatalog' | 'approaches' | 'approachCatalog' | 'texture' | 'smell' |
  'taste' | 'presentation' | 'temperature' | 'familiarity';

const options: Record<OptionGroup, Option[]> = {
  age: [
    ['toddler', '1–3 years', '1–3세'], ['preschool', '4–6 years', '4–6세'],
    ['school', '7–12 years', '7–12세'], ['teen', '13–17 years', '13–17세'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  allergies: [
    ['peanut', 'Peanuts', '땅콩'], ['tree-nut', 'Tree nuts', '견과류'],
    ['milk', 'Milk / Dairy', '우유 / 유제품'], ['egg', 'Eggs', '달걀'],
    ['soy', 'Soy', '대두'], ['wheat', 'Wheat', '밀'],
    ['fish', 'Fish', '생선'], ['shellfish', 'Shellfish', '갑각류'], ['sesame', 'Sesame', '참깨'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  allergyCatalog: [
    ['coconut', 'Coconut', '코코넛'], ['buckwheat', 'Buckwheat', '메밀'],
    ['kiwi', 'Kiwi', '키위'], ['strawberry', 'Strawberry', '딸기'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  restrictions: [
    ['gluten-free', 'Gluten free', '글루텐 제한'], ['lactose-free', 'Lactose free', '유당 제한'],
    ['low-sodium', 'Low sodium', '저염식'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  restrictionCatalog: [
    ['no-pork', 'No pork', '돼지고기 제외'], ['no-beef', 'No beef', '소고기 제외'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  family: [
    ['vegetables', 'Vegetables', '채소'], ['fruits', 'Fruits', '과일'],
    ['grains', 'Grains', '곡류'], ['meat', 'Meat', '육류'],
    ['fish', 'Fish', '생선'], ['dairy', 'Dairy', '유제품'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  familyCatalog: [
    ['legumes', 'Legumes', '콩류'], ['eggs', 'Eggs', '달걀'], ['seaweed', 'Seaweed', '해조류'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  approaches: [
    ['vegetarian', 'Vegetarian', '채식'], ['vegan', 'Vegan', '비건'],
    ['halal', 'Halal', '할랄'], ['kosher', 'Kosher', '코셔'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  approachCatalog: [
    ['pescatarian', 'Pescatarian', '페스코'], ['mediterranean', 'Mediterranean', '지중해식'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  texture: [
    ['smooth', 'Smooth or creamy', '부드럽거나 크림 같은'],
    ['lumpy', 'Lumpy', '덩어리가 있는'], ['crunchy', 'Crunchy', '바삭한'],
    ['chewy', 'Chewy', '질긴'], ['slippery', 'Slippery', '미끄러운'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  smell: [
    ['yes', 'Yes', '네'], ['sometimes', 'Sometimes', '가끔'],
    ['no', 'No', '아니요'], ['unsure', 'Not sure', '잘 모르겠어요'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  taste: [
    ['sweet', 'Sweet', '단맛'], ['salty', 'Salty', '짠맛'],
    ['sour', 'Sour', '신맛'], ['bitter', 'Bitter', '쓴맛'], ['spicy', 'Spicy', '매운맛'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  presentation: [
    ['color', 'Color', '색'], ['shape', 'Shape and size', '모양과 크기'],
    ['separate', 'Foods kept separate', '음식이 닿지 않게'],
    ['visible', 'Ingredients visible', '재료가 보이게'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  temperature: [
    ['none', 'No clear preference', '뚜렷한 선호 없음'], ['warm', 'Warm', '따뜻하게'],
    ['cool', 'Cool / chilled', '차갑게'], ['room', 'Room temperature', '상온'],
    ['depends', 'It depends on the food', '음식마다 달라요'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
  familiarity: [
    ['tastes', 'Usually tastes a new food', '새 음식을 보통 맛봐요'],
    ['plate', 'Okay on the plate, may not taste', '접시에 놓여도 괜찮지만 먹지 않을 수 있어요'],
    ['nearby', 'Prefers it nearby but separate', '가까이 두되 분리하는 편이에요'],
    ['removed', 'Wants it removed', '치워 주길 원해요'],
    ['varies', 'Varies by food', '음식마다 달라요'], ['unsure', 'Not sure', '잘 모르겠어요'],
  ].map(([id, en, ko]) => ({ id, label: { en, ko } })),
};

export function optionsFor(group: OptionGroup, language: Language) {
  return options[group].map(({ id, label }) => ({ id, label: label[language] }));
}

export function labelFor(group: OptionGroup, id: string, language: Language): string {
  if (id === 'none') return strings[language].common.none;
  const catalog: Partial<Record<OptionGroup, OptionGroup>> = {
    allergies: 'allergyCatalog', restrictions: 'restrictionCatalog',
    family: 'familyCatalog', approaches: 'approachCatalog',
  };
  return options[group].find((option) => option.id === id)?.label[language]
    ?? (catalog[group] ? options[catalog[group]].find((option) => option.id === id)?.label[language] : undefined)
    ?? id;
}
