// This Code is generated with AI

import { StyleSheet } from 'react-native';
import { colors } from '../util/colors';
import { fonts } from '../util/fonts';
export const formStyles = StyleSheet.create({
  text: {
    color: colors.homeText,
    fontSize: 11,
    fontFamily: fonts.poppinsRegular,
    lineHeight: 17,
  },
  muted: {
    color: colors.homeMuted,
    fontSize: 10,
    fontFamily: fonts.poppinsRegular,
    lineHeight: 16,
  },
  heading: {
    color: colors.homeText,
    fontSize: 17,
    fontFamily: fonts.poppinsSemiBold,
  },
  title: {
    color: colors.homeText,
    fontSize: 24,
    fontFamily: fonts.poppinsSemiBold,
    lineHeight: 31,
  },
  label: {
    color: colors.homeText,
    fontSize: 10,
    fontFamily: fonts.poppinsSemiBold,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  stack: { gap: 10 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.homeBorder,
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  info: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.infoSurface,
    gap: 8,
  },
  error: {
    color: colors.error,
    fontFamily: fonts.poppinsRegular,
    fontSize: 11,
    lineHeight: 18,
  },
  link: {
    color: colors.homePrimary,
    fontFamily: fonts.poppinsSemiBold,
    fontSize: 11,
  },
  choice: {
    minHeight: 46,
    backgroundColor: colors.surface,
    borderColor: colors.homeBorder,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tile: {
    width: '48%',
    flexGrow: 1,
    minHeight: 76,
    borderRadius: 16,
    padding: 14,
    gap: 12,
    shadowColor: colors.navy,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 24,
    elevation: 2,
  },
  choiceText: { flex: 1, fontSize: 12, fontFamily: fonts.poppinsSemiBold },
  tileText: { fontSize: 14, lineHeight: 19 },
  selected: {
    borderColor: colors.homePrimary,
    backgroundColor: colors.homeSelected,
    borderWidth: 2,
  },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.homeBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioSelected: { borderColor: colors.homePrimary, backgroundColor: colors.homePrimary },
  icon: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: colors.homeBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tag: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.homeSelected,
  },
  scrim: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  dialogScrim: { justifyContent: 'center' },
  dismiss: { flex: 1 },
  sheet: {
    maxHeight: '90%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 18,
    paddingTop: 9,
  },
  dialog: { maxHeight: '88%', marginHorizontal: 8, borderRadius: 30, paddingHorizontal: 16, paddingBottom: 14, width: 'auto' },
  dialogHeading: { fontSize: 20 },
  sheetContent: { paddingVertical: 16, gap: 12 },
  sheetFooter: { paddingVertical: 10 },
  handle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.homeBorder,
    alignSelf: 'center',
    marginBottom: 12,
  },
  close: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: colors.homeBackground,
  },
});
