import { StyleSheet } from 'react-native';
import { colors } from '../../../util/colors';
import { fonts } from '../../../util/fonts';

export const styles = StyleSheet.create({
  sectionLabel: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interExtraBold,
    marginBottom: 6,
  },
  chip: {
    borderRadius: 999,
    backgroundColor: colors.onboardingSelected,
    borderWidth: 1,
    borderColor: colors.onboardingPrimary,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  chipText: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interBold,
  },
  consentPanel: {
    backgroundColor: colors.onboardingSelected,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    padding: 9,
    marginBottom: 8,
  },
  consentPanelSelected: { borderColor: colors.onboardingPrimary },
  consentPanelTitle: {
    color: colors.onboardingText,
    fontSize: 11,
    fontFamily: fonts.interBold,
  },
  consentPanelSubtitle: {
    color: colors.onboardingMuted,
    fontSize: 9,
    fontFamily: fonts.interRegular,
    marginTop: 2,
    marginBottom: 7,
  },
  consentCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    padding: 9,
    marginBottom: 7,
  },
  selectedConsentCard: {
    backgroundColor: colors.onboardingSelected,
    borderColor: colors.onboardingPrimary,
  },
  consentRow: { flexDirection: 'row', gap: 8 },
  consentCheck: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  consentChecked: {
    backgroundColor: colors.onboardingPrimary,
    borderColor: colors.onboardingPrimary,
  },
  consentCopy: { flex: 1, gap: 3 },
  consentTitle: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interBold,
  },
  consentRequired: {
    color: colors.onboardingMuted,
    fontSize: 8,
    fontFamily: fonts.interMedium,
  },
  consentDescription: {
    color: colors.onboardingMuted,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: fonts.interRegular,
  },
  detail: {
    color: colors.onboardingPrimary,
    fontSize: 8,
    fontFamily: fonts.interMedium,
    marginTop: 2,
  },
  safetyBanner: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: colors.safetySurface,
    borderRadius: 11,
    padding: 8,
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  safetyIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  safetyCopy: { flex: 1, gap: 2 },
  safetyTitle: {
    color: colors.error,
    fontSize: 10,
    fontFamily: fonts.interMedium,
  },
  safetyText: {
    color: colors.onboardingText,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: fonts.interRegular,
    flex: 1,
  },
  safeFoodChip: {
    borderRadius: 10,
    backgroundColor: colors.onboardingSelected,
    padding: 11,
    marginBottom: 8,
  },
  openSafeFood: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    borderRadius: 10,
    marginTop: 12,
    paddingHorizontal: 12,
    minHeight: 46,
  },
  openSafeFoodText: {
    color: colors.onboardingText,
    fontSize: 13,
    fontWeight: '700',
  },
  plus: { color: colors.onboardingPrimary, fontSize: 22, fontWeight: '800' },
  safeFoodForm: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    padding: 12,
    marginTop: 12,
  },
  warning: {
    color: colors.error,
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    fontSize: 12,
    lineHeight: 18,
  },
});
