import { StyleSheet } from 'react-native';
import { colors } from '../../../util/colors';
import { fonts } from '../../../util/fonts';

export const styles = StyleSheet.create({
  sectionLabel: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interExtraBold,
    marginBottom: 6,
    marginTop: 10,
    textTransform: 'uppercase',
  },
  fieldHint: { color: colors.onboardingMuted, fontSize: 8, fontFamily: fonts.interRegular, marginTop: -4 },
  question: { color: colors.onboardingText, fontSize: 13, lineHeight: 16, fontFamily: fonts.interBold, marginBottom: 7 },
  questionHelper: { color: colors.onboardingMuted, fontSize: 8, lineHeight: 11, fontFamily: fonts.interRegular, marginTop: -5, marginBottom: 7 },
  selectionHint: { color: colors.onboardingMuted, fontSize: 8, fontFamily: fonts.interRegular, textAlign: 'right', marginTop: 3, marginBottom: 6 },
  infoBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: colors.homeSelected, borderRadius: 11, padding: 8, marginTop: 8, marginBottom: 8 },
  infoIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
  infoTitle: { color: colors.onboardingPrimary, fontSize: 10, fontFamily: fonts.interMedium },
  infoText: { color: colors.onboardingText, fontSize: 9, lineHeight: 12, fontFamily: fonts.interRegular },
  chip: {
    borderRadius: 999,
    backgroundColor: colors.onboardingSelected,
    borderWidth: 1,
    borderColor: colors.onboardingPrimary,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  chipText: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interBold,
  },
  consentPanel: {
    backgroundColor: colors.homeSelected,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.mealReviewBorder,
    padding: 10,
    marginBottom: 8,
  },
  consentPanelSelected: { borderColor: colors.onboardingPrimary },
  consentPanelTitle: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interExtraBold,
  },
  consentPanelSubtitle: {
    color: colors.onboardingMuted,
    fontSize: 8,
    fontFamily: fonts.interRegular,
    marginTop: 2,
    marginBottom: 7,
  },
  consentCard: {
    backgroundColor: colors.surface,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    padding: 9,
    marginBottom: 7,
  },
  selectedConsentCard: {
    backgroundColor: colors.onboardingSelected,
    borderColor: colors.onboardingPrimary,
  },
  consentPressable: { gap: 6 },
  consentRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  consentCheck: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  consentChecked: {
    backgroundColor: colors.onboardingPrimary,
    borderColor: colors.onboardingPrimary,
  },
  consentCopy: { gap: 3 },
  consentTitle: {
    color: colors.onboardingText,
    fontSize: 10,
    fontFamily: fonts.interExtraBold,
    flex: 1,
  },
  consentBadge: { borderWidth: 1, borderColor: colors.onboardingPrimary, backgroundColor: colors.homeSelected, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 2 },
  consentOptionalBadge: { borderColor: colors.onboardingBorder },
  consentRequired: {
    color: colors.onboardingPrimary,
    fontSize: 7,
    fontFamily: fonts.interExtraBold,
    textTransform: 'uppercase',
  },
  consentOptional: { color: colors.onboardingMuted },
  consentDescription: {
    color: colors.onboardingMuted,
    fontSize: 8,
    lineHeight: 11,
    fontFamily: fonts.interRegular,
  },
  detail: {
    color: colors.homeSubtitle,
    fontSize: 8,
    fontFamily: fonts.interRegular,
    marginTop: 2,
  },
  safetyBanner: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: colors.safetySurface,
    borderRadius: 11,
    padding: 8,
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  safetyIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  safetyCopy: { flex: 1, gap: 2 },
  safetyTitle: {
    color: colors.error,
    fontSize: 10,
    fontFamily: fonts.interMedium,
  },
  safetyText: {
    color: colors.onboardingText,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: fonts.interRegular,
    flex: 1,
  },
  safeFoodChip: {
    borderRadius: 10,
    backgroundColor: colors.onboardingSelected,
    padding: 11,
    marginBottom: 8,
  },
  safeFoodAddRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  safeFoodQuickInput: { flex: 1, height: 40, borderWidth: 1, borderColor: colors.onboardingBorder, borderRadius: 8, backgroundColor: colors.surface, paddingHorizontal: 10, color: colors.onboardingText, fontSize: 10, fontFamily: fonts.interRegular },
  safeFoodPlaceholder: { color: colors.homeSubtitle },
  safeFoodAddButton: { width: 40, height: 40, borderRadius: 8, backgroundColor: colors.onboardingPrimary, alignItems: 'center', justifyContent: 'center' },
  safeFoodAddPlus: { color: colors.surface, fontSize: 22, fontFamily: fonts.interMedium, lineHeight: 26 },
  multipleHint: { color: colors.onboardingMuted, fontSize: 8, fontFamily: fonts.interRegular, textAlign: 'right', marginTop: 3 },
  safeFoodFormTitle: { color: colors.onboardingText, fontSize: 16, fontFamily: fonts.interBold },
  safeFoodFormSubtitle: { color: colors.onboardingMuted, fontSize: 9, fontFamily: fonts.interRegular, marginBottom: 10 },
  openSafeFood: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    borderRadius: 10,
    marginTop: 12,
    paddingHorizontal: 12,
    minHeight: 46,
  },
  openSafeFoodText: {
    color: colors.onboardingText,
    fontSize: 13,
    fontWeight: '700',
  },
  plus: { color: colors.onboardingPrimary, fontSize: 22, fontWeight: '800' },
  safeFoodForm: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.onboardingBorder,
    padding: 15,
    marginTop: 8,
    shadowColor: colors.navy,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 20,
    elevation: 2,
  },
  warning: {
    color: colors.error,
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    fontSize: 12,
    lineHeight: 18,
  },
});
